version: 2

models:
  - name: operadoras
    description: "Tabela de operadoras de transporte"
    columns:
      - name: id_operadora
        description: "Identificador único do operador, podendo ser o código de permissionário ou código da Jaé"
      - name: operadora
        description: "Nome do operador (mascarado quando o operador é pessoa física)"
      - name: operadora_completo
        description: "Nome do operador [protegido]"
        policy_tags:
          - 'projects/rj-smtr/locations/us/taxonomies/388050497607535163/policyTags/3935188996031375059'
      - name: tipo_operadora
        description: "Tipo de permissionário (Exemplos: autônomo, empresa, cooperativa)"
      - name: modo
        description: "Modo de transporte do operador, podendo ser o modo na Jaé ou no STU"
      - name: modo_stu
        description: "Modo de transporte no STU (ônibus, van, BRT)"
      - name: modo_jae
        description: "Modo de transporte na Jaé (ônibus, van, BRT)"
      - name: id_processo
        description: "Número do processo no STU"
      - name: data_processo
        description: "Data do processo no STU"
      - name: documento
        description: "{{ doc('documento_operadora') }}"
        policy_tags:
          - 'projects/rj-smtr/locations/us/taxonomies/388050497607535163/policyTags/3935188996031375059'
      - name: tipo_documento
        description: "{{ doc('tipo_documento_operadora') }}"
      - name: id_operadora_stu
        description: "Código de permissionário vindo do STU"
      - name: id_operadora_jae
        description: "Código do operador no sistema da Jaé"
      - name: indicador_operador_ativo_jae
        description: "Indicador de atividade do operador no sistema da Jaé"
      - name: agencia
        description: "Número da agência bancária do operador [protegido]"
        policy_tags:
          - 'projects/rj-smtr/locations/us/taxonomies/388050497607535163/policyTags/3935188996031375059'
      - name: tipo_conta
        description: "Tipo da conta bancária do operador [protegido]"
        policy_tags:
          - 'projects/rj-smtr/locations/us/taxonomies/388050497607535163/policyTags/3935188996031375059'
      - name: banco
        description: "Nome do banco [protegido]"
        policy_tags:
          - 'projects/rj-smtr/locations/us/taxonomies/388050497607535163/policyTags/3935188996031375059'
      - name: codigo_banco
        description: "Código do banco (COMPE) [protegido]"
        policy_tags:
          - 'projects/rj-smtr/locations/us/taxonomies/388050497607535163/policyTags/3935188996031375059'
      - name: conta
        description: "Número da conta bancária do operador [protegido]"
        policy_tags:
          - 'projects/rj-smtr/locations/us/taxonomies/388050497607535163/policyTags/3935188996031375059'
  - name: operadoras_contato
    description: "Tabela de contatos das operadoras de transporte"
    columns:
      - name: id_operadora
        description: "Identificador único da tabela cadastro.operadoras"
      - name: contato
        description: "Nome do contato [protegido]"
        policy_tags:
          - 'projects/rj-smtr/locations/us/taxonomies/388050497607535163/policyTags/3935188996031375059'
      - name: ramal
        description: "Ramal do telefone [protegido]"
        policy_tags:
          - 'projects/rj-smtr/locations/us/taxonomies/388050497607535163/policyTags/3935188996031375059'
      - name: telefone
        description: "Número de telefone [protegido]"
        policy_tags:
          - 'projects/rj-smtr/locations/us/taxonomies/388050497607535163/policyTags/3935188996031375059'
      - name: email
        description: "Endereço de E-Mail [protegido]"
        policy_tags:
          - 'projects/rj-smtr/locations/us/taxonomies/388050497607535163/policyTags/3935188996031375059'
  - name: consorcios
    description: "Tabela com dados unificados de consorcios"
    columns:
      - name: id_consorcio
        description: "{{ doc('id_consorcio') }}"
      - name: consorcio
        description: "{{ doc('nome_consorcio') }}"
      - name: modo
        description: "Modo de transporte do consórcio"
      - name: id_processo
        description: "Número do processo no STU"
      - name: data_processo
        description: "Data do processo no STU"
      - name: cnpj
        description: "CNPJ do consórcio"
      - name: razao_social
        description: "Razão social do consórcio"
      - name: id_consorcio_stu
        description: "Código de permissionário vindo do STU"
      - name: id_consorcio_jae
        description: "Código do consórcio no sistema da Jaé"
  - name: servicos
    description: "Tabela com dados unificados de serviços (linhas e estações)"
    columns:
      - name: id_servico_gtfs
        description: "Identificador único do serviço no GTFS, podendo ser o stop_id (no caso de estações) ou o route_id (no caso de linhas)"
      - name: id_servico_jae
        description: "{{ doc('id_servico_jae') }}"
      - name: servico
        description: "{{ doc('servico_cadastro') }}"
      - name: servico_gtfs
        description: "Nome do serviço consolidado. Para linhas, é a coluna route_short_name da tabela routes do GTFS, que contém o nome curto da linha (ex: 010, 011SN). Para estações, é a coluna stop_code da tabela stops do GTFS"
      - name: servico_jae
        description: "{{ doc('servico_jae') }}"
      - name: descricao_servico
        description: "{{ doc('descricao_servico_cadastro') }}"
      - name: descricao_servico_gtfs
        description: "Nome completo do serviço no GTFS [Para linhas é primariamente o route_long_name da tabela routes do GTFS, para estações é primariamente a coluna stop_name da tabela stops do GTFS]"
      - name: descricao_servico_jae
        description: "{{ doc('descricao_servico_jae') }}"
      - name: latitude
        description: "Latitude da estação na tabela stops do GTFS"
      - name: longitude
        description: "Longitude da estação na tabela stops do GTFS"
      - name: tabela_origem_gtfs
        description: "Tabela do GTFS de onde foram coletadas as informações (stops ou routes)"
      - name: feed_start_date_gtfs
        description: "Último feed_start_date do GTFS em que as informações do serviço estavam disponíveis"
      - name: data_inicio_vigencia
        description: "Data de inicio da vigência do serviço segundo o GTFS ou o cadastro do serviço no sistema da Jaé (caso não exista no GTFS)"
      - name: data_fim_vigencia
        description: "Data de fim da vigência do serviço segundo o GTFS"
      - name: versao
        description: "{{ doc('versao') }}"
  - name: servico_operadora
    description: "Tabela com a relação entre serviço, consorcio e operadora de transporte de acordo com a base da Jaé"
    columns:
      - name: id_consorcio
        description: "{{ doc('id_consorcio') }}"
        data_type: string
      - name: consorcio
        description: "{{ doc('consorcio') }}"
        data_type: string
      - name: id_operadora
        description: "Identificador único do operador, podendo ser o código de permissionário ou código da Jaé"
        data_type: string
      - name: operadora
        description: "Nome do operador (mascarado quando o operador é pessoa física)"
        data_type: string
      - name: servico
        description: "Nome do serviço consolidado. Para linhas, é o nome curto da linha (ex: 010, 011SN). E para estações, é o stop_code do GTFS ou o código interno da estação no banco de dados da Jaé. (Caso o registro não exista no GTFS, busca o serviço na base de dados da Jaé)"
      - name: id_servico_jae
        description: "Identificador único do serviço no banco de dados da Jaé"
        data_type: string
      - name: descricao_servico
        description: "Nome completo do serviço consolidado. Para linhas é, primariamente o route_long_name da tabela routes do GTFS. Para estações é primariamente a coluna stop_name da tabela stops do GTFS. (Caso o registro não exista no GTFS, busca o nome do serviço na base de dados da Jaé)"
      - name: data_inicio_validade
        description: "Data de inicio da validade do registro"
        data_type: datetime
      - name: data_fim_validade
        description: "Data de fim da validade do registro"
        data_type: datetime
      - name: versao
        description: "{{ doc('versao') }}"
        data_type: string
      - name: modo
        description: "{{ doc('modo') }}"
        data_type: string
        quote: true
      - name: servico_jae
        description: "{{ doc('servico_variacao') }} ou código da estação de BRT na Jaé"
        data_type: string
        quote: true
      - name: descricao_servico_jae
        description: "Nome longo da linha operada pelo veículo com variação de serviço (ex: 010, 011SN, ...) ou nome da estação de BRT na Jaé"
        data_type: string
        quote: true
      - name: id_servico_gtfs
        description: Identificador único do serviço no GTFS, podendo ser o stop_id (no caso de estações) ou o route_id (no caso de linhas)
        data_type: string
        quote: true
      - name: tabela_origem_gtfs
        description: Tabela do GTFS que o id_servico_gtfs pertence
        data_type: string
        quote: true
      - name: tarifa_ida
        description: Valor da tarifa no sentido Ida
        data_type: numeric
        quote: true
      - name: tarifa_volta
        description: Valor da tarifa no sentido Volta
        data_type: numeric
        quote: true
  - name: veiculo_licenciamento_dia
    description: Tabela histórica de dados cadastrais dos veículos que operam o sistema de transporte rodoviário, considerando tanto os licenciados no Sistema de Transporte Urbano [STU] quanto as solicitações válidas em andamento para ingresso no sistema [contém dados a partir de 2025-04-01]
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
          - data
          - id_veiculo
          - data_processamento
          name: dbt_utils.unique_combination_of_columns__veiculo_licenciamento_dia
      - test_check_data_arquivo_licenciamento:
          name: test_check_data_arquivo_licenciamento__veiculo_licenciamento_dia
    columns:
      - name: data
        description: Data [partição]
        data_type: date
        quote: true
        tests:
          - not_null:
              name: not_null__data__veiculo_licenciamento_dia
      - name: data_processamento
        description: Data em que as informações do veículo foram atualizadas nesta tabela
        data_type: date
        quote: true
        tests:
          - not_null:
              name: not_null__data_processamento__veiculo_licenciamento_dia
      - name: id_veiculo
        description: "{{ doc('id_veiculo') }}"
        data_type: string
        quote: true
        tests:
          - not_null:
              name: not_null__id_veiculo__veiculo_licenciamento_dia
      - name: placa
        description: "{{ doc('placa') }}"
        data_type: string
        quote: true
        tests:
          - not_null:
              name: not_null__placa__veiculo_licenciamento_dia
      - name: modo
        description: "{{ doc('modo') }}"
        data_type: string
        quote: true
        tests:
          - not_null:
              name: not_null__modo__veiculo_licenciamento_dia
      - name: permissao
        description: "{{ doc('permissao') }}"
        data_type: string
        quote: true
      - name: ano_fabricacao
        description: "{{ doc('ano_fabricacao') }} [chassi]"
        data_type: int64
        quote: true
        tests:
          - not_null:
              name: not_null__ano_fabricacao__veiculo_licenciamento_dia
      - name: id_carroceria
        description: "{{ doc('id_carroceria') }}"
        data_type: int64
        quote: true
      - name: id_interno_carroceria
        description: "{{ doc('id_interno_carroceria') }}"
        data_type: int64
        quote: true
      - name: carroceria
        description: "{{ doc('carroceria') }}"
        data_type: string
        quote: true
      - name: id_chassi
        description: "{{ doc('id_chassi') }}"
        data_type: int64
        quote: true
      - name: id_fabricante_chassi
        description: "{{ doc('id_fabricante_chassi') }}"
        data_type: int64
        quote: true
      - name: nome_chassi
        description: "{{ doc('nome_chassi') }}"
        data_type: string
        quote: true
      - name: id_planta
        description: "{{ doc('id_planta') }}"
        data_type: int64
        quote: true
      - name: tipo_veiculo
        description: "{{ doc('tipo_veiculo') }}"
        data_type: string
        quote: true
        tests:
          - not_null:
              name: not_null__tipo_veiculo__veiculo_licenciamento_dia
              where: "data between date('{date_range_start}') and date('{date_range_end}') and modo = 'ONIBUS'"
      - name: status
        description: Status do veículo
        data_type: string
        quote: true
      - name: data_inicio_vinculo
        description: "{{ doc('data_inicio_vinculo') }}"
        data_type: date
        quote: true
        tests:
          - not_null:
              name: not_null__data_inicio_vinculo__veiculo_licenciamento_dia
      - name: data_ultima_vistoria
        description: "{{ doc('data_ultima_vistoria') }}"
        data_type: date
        quote: true
      - name: ano_ultima_vistoria
        description: "{{ doc('ano_ultima_vistoria_atualizado') }}"
        data_type: int64
        quote: true
      - name: ultima_situacao
        description: Última situação do veículo na data atual
        data_type: string
        quote: true
        tests:
          - not_null:
              name: not_null__ultima_situacao__veiculo_licenciamento_dia
      - name: tecnologia
        description: "{{ doc('tecnologia') }}"
        data_type: string
        quote: true
      - name: quantidade_lotacao_pe
        description: "{{ doc('quantidade_lotacao_pe') }}"
        data_type: int64
        quote: true
      - name: quantidade_lotacao_sentado
        description: "{{ doc('quantidade_lotacao_sentado') }}"
        data_type: int64
        quote: true
      - name: tipo_combustivel
        description: "{{ doc('tipo_combustivel') }}"
        data_type: string
        quote: true
      - name: indicador_ar_condicionado
        description: "{{ doc('indicador_ar_condicionado') }}"
        data_type: boolean
        quote: true
      - name: indicador_elevador
        description: "{{ doc('indicador_elevador') }}"
        data_type: boolean
        quote: true
      - name: indicador_usb
        description: "{{ doc('indicador_usb') }}"
        data_type: boolean
        quote: true
      - name: indicador_wifi
        description: "{{ doc('indicador_wifi') }}"
        data_type: boolean
        quote: true
      - name: indicador_veiculo_lacrado
        description: Indicador se o veículo estava lacrado na data atual [Verdadeiro/Falso]
        data_type: boolean
        quote: true
      - name: data_arquivo_fonte
        description: data do arquivo do STU com os dados utilizados
        data_type: date
        quote: true
        tests:
          - not_null:
              name: not_null__data_arquivo_fonte__veiculo_licenciamento_dia
      - name: versao
        description: "{{ doc('versao') }}"
        data_type: string
        quote: true
      - name: datetime_ultima_atualizacao
        description: "{{ doc('datetime_ultima_atualizacao') }}"
        data_type: datetime
        quote: true
      - name: id_execucao_dbt
        description: "{{ doc('id_execucao_dbt') }}"
        data_type: string
        quote: true
  - name: modos
    description: Tabela dos tipos de transporte
    columns:
      - name: id_modo
        description: Identificador
      - name: modo
        description: "{{ doc('modo') }}"
      - name: fonte
        description: Fonte de origem dos dados
