version: 2

models:
  - name: infracao
    description: "Tabela histórica de todas as multas aplicadas aos modos de transporte no município do Rio de Janeiro, com qualquer situação"
    tests:
      - dbt_expectations.expect_table_aggregation_to_equal_other_table:
          name: dbt_expectations.expect_table_aggregation_to_equal_other_table__infracao
          expression: count(distinct data)
          compare_model: ref('infracao_staging')
          compare_expression: count(distinct data)
          group_by: [data]
          compare_group_by: [Date(data)]
          row_condition: "DATE(data) between DATE('{{ modules.datetime.datetime.fromisoformat(var('date_range_start')) + modules.datetime.timedelta(7) }}') AND DATE('{{ modules.datetime.datetime.fromisoformat(var('date_range_end')) + modules.datetime.timedelta(8) }}')"
          compare_row_condition: "DATE(data) between DATE('{{ modules.datetime.datetime.fromisoformat(var('date_range_start')) + modules.datetime.timedelta(7) }}') AND DATE('{{ modules.datetime.datetime.fromisoformat(var('date_range_end')) + modules.datetime.timedelta(8) }}')"
          where: "DATE(data) between DATE('{{ modules.datetime.datetime.fromisoformat(var('date_range_start')) + modules.datetime.timedelta(7) }}') AND DATE('{{ modules.datetime.datetime.fromisoformat(var('date_range_end')) + modules.datetime.timedelta(8) }}')"
    columns:
      - name: data
        description: "{{ doc('data_captura') }} [partição]"
      - name: timestamp_captura
        description: "Timestamp de captura dos dados de infração"
      - name: modo
        description: "ÔNIBUS – nesse arquivo só constam os ônibus"
      - name: permissao
        description: "{{ doc('permissao') }}"
      - name: placa
        description: "{{ doc('placa') }}"
      - name: servico
        description: "{{ doc('servico') }}"
      - name: id_auto_infracao
        description: "Identificador do auto de infração da multa aplicada"
      - name: data_infracao
        description: "Data da infração"
      - name: valor
        description: "Valor devido (R$)"
      - name: id_infracao
        description: "Código da infração"
      - name: infracao
        description: "Descrição da infração"
      - name: status
        description: "CADASTRADA - Registrada no sistema sem guia de pagamento\n
                      EM ABERTO - Com guia de pagamento e dentro do prazo de vencimento\n
                      VENCIDA - Com guia de pagamento e fora do prazo de vencimento\n
                      EM RECURSO - Possui Processo de Recurso aguardando julgamento\n
                      PAGA - Com guia de pagamento efetivamente paga\n
                      CANCELADA - Multa foi cancelada através de um Processo de Recurso"
      - name: data_pagamento
        description: "Data de pagamento"
      - name: datetime_ultima_atualizacao
        description: "{{ doc('datetime_ultima_atualizacao') }}"
      - name: versao
        description: "{{ doc('versao') }}"
  - name: licenciamento
    description: "Tabela histórica de dados cadastrais dos veículos que operam o sistema de transporte rodoviário,
                  considerando tanto os licenciados no Sistema de Transporte Urbano [STU] quanto as solicitações
                  válidas em andamento para ingresso no sistema"
    columns:
      - name: data
        description: "{{ doc('data_captura') }} [partição]"
      - name: modo
        description: "{{ doc('modo') }}"
      - name: id_veiculo
        description: "{{ doc('id_veiculo') }}"
      - name: ano_fabricacao
        description: "{{ doc('ano_fabricacao') }} [chassi]"
      - name: carroceria
        description: "{{ doc('carroceria') }}"
      - name: data_ultima_vistoria
        description: "{{ doc('data_ultima_vistoria') }}"
      - name: id_carroceria
        description: "{{ doc('id_carroceria') }}"
      - name: id_chassi
        description: "{{ doc('id_chassi') }}"
      - name: id_fabricante_chassi
        description: "{{ doc('id_fabricante_chassi') }}"
      - name: id_interno_carroceria
        description: "{{ doc('id_interno_carroceria') }}"
      - name: id_planta
        description: "{{ doc('id_planta') }}"
      - name: indicador_ar_condicionado
        description: "{{ doc('indicador_ar_condicionado') }}"
      - name: indicador_elevador
        description: "{{ doc('indicador_elevador') }}"
      - name: indicador_usb
        description: "{{ doc('indicador_usb') }}"
      - name: indicador_wifi
        description: "{{ doc('indicador_wifi') }}"
      - name: nome_chassi
        description: "{{ doc('nome_chassi') }}"
      - name: permissao
        description: "{{ doc('permissao') }}"
      - name: placa
        description: "{{ doc('placa') }}"
      - name: quantidade_lotacao_pe
        description: "{{ doc('quantidade_lotacao_pe') }}"
      - name: quantidade_lotacao_sentado
        description: "{{ doc('quantidade_lotacao_sentado') }}"
      - name: tipo_combustivel
        description: "{{ doc('tipo_combustivel') }}"
      - name: tipo_veiculo
        description: "{{ doc('tipo_veiculo') }}"
      - name: tecnologia
        description: "{{ doc('tecnologia') }}"
      - name: status
        description: "{{ doc('status') }}"
      - name: ano_ultima_vistoria_atualizado
        description: "{{ doc('ano_ultima_vistoria_atualizado') }}"
      - name: data_inicio_vinculo
        description: "{{ doc('data_inicio_vinculo') }}"
      - name: datetime_ultima_atualizacao
        description: "{{ doc('datetime_ultima_atualizacao') }}"
      - name: versao
        description: "{{ doc('versao') }}"
  - name: sppo_licenciamento_solicitacao
    description: "Tabela histórica de dados cadastrais das solicitações em andamento para ingresso no Sistema de Transporte Urbano [STU]"
    columns:
      - name: data
        description: "{{ doc('data_captura') }} [partição]"
      - name: timestamp_captura
        description: "Timestamp de captura dos dados de licenciamento"
      - name: modo
        description: "ÔNIBUS – nesse arquivo só constam os ônibus"
      - name: id_veiculo
        description: "{{ doc('id_veiculo') }}"
      - name: ano_fabricacao
        description: "{{ doc('ano_fabricacao') }}"
      - name: carroceria
        description: "{{ doc('carroceria') }}"
      - name: data_ultima_vistoria
        description: "{{ doc('data_ultima_vistoria') }}"
      - name: id_carroceria
        description: "{{ doc('id_carroceria') }}"
      - name: id_chassi
        description: "{{ doc('id_chassi') }}"
      - name: id_fabricante_chassi
        description: "{{ doc('id_fabricante_chassi') }}"
      - name: id_interno_carroceria
        description: "{{ doc('id_interno_carroceria') }}"
      - name: id_planta
        description: "{{ doc('id_planta') }}"
      - name: indicador_ar_condicionado
        description: "{{ doc('indicador_ar_condicionado') }}"
      - name: indicador_elevador
        description: "{{ doc('indicador_elevador') }}"
      - name: indicador_usb
        description: "{{ doc('indicador_usb') }}"
      - name: indicador_wifi
        description: "{{ doc('indicador_wifi') }}"
      - name: nome_chassi
        description: "{{ doc('nome_chassi') }}"
      - name: permissao
        description: "{{ doc('permissao') }}"
      - name: placa
        description: "{{ doc('placa') }}"
      - name: quantidade_lotacao_pe
        description: "{{ doc('quantidade_lotacao_pe') }}"
      - name: quantidade_lotacao_sentado
        description: "{{ doc('quantidade_lotacao_sentado') }}"
      - name: tipo_combustivel
        description: "{{ doc('tipo_combustivel') }}"
      - name: tipo_veiculo
        description: "{{ doc('tipo_veiculo') }}"
      - name: status
        description: "{{ doc('status') }}"
      - name: solicitacao
        description: "Inclusão - Solicitação de ingresso de veículo no Sistema de Transporte Urbano [STU]\n
                      Baixa - Solicitação de baixa de veículo já incluído no Sistema de Transporte Urbano [STU]\n
                      Renumeração - Solicitação de alteração de número de ordem de veículo já incluído no Sistema de Transporte Urbano [STU]"
  - name: sppo_veiculo_dia
    description: "Tabela resumo dos veículos que operaram no SPPO e seus respectivos indicadores"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
          - data
          - id_veiculo
          name: dbt_utils.unique_combination_of_columns__data_id_veiculo__sppo_veiculo_dia
    columns:
      - name: data
        description: "Data de operação"
      - name: id_veiculo
        description: "{{ doc('id_veiculo') }}"
      - name: placa
        description: "{{ doc('placa') }}"
      - name: indicadores
        description: "Indicadores para caraterização do status do veículo"
      - name: indicadores.indicador_licenciado
        description: "Indicador se o veículo encontra-se licenciado"
      - name: indicadores.indicador_ar_condicionado
        description: "Indicador se o veículo foi licenciado com ar condicionado"
      - name: indicadores.indicador_autuacao_ar_condicionado
        description: "Indicador se o veículo foi autuado por inoperância ou mau funcionamento do sistema de ar condicionado"
      - name: indicadores.indicador_autuacao_seguranca
        description: "Indicador se o veículo foi autuado por infração relacionada à segurança do veículo"
      - name: indicadores.indicador_autuacao_limpeza
        description: "Indicador se o veículo foi autuado por infração relacionada à limpeza do veículo"
      - name: indicadores.indicador_autuacao_equipamento
        description: "Indicador se o veículo foi autuado por infração relacionada à inoperância ou mau funcionamento de equipamentos do veículo"
      - name: indicadores.indicador_sensor_temperatura
        description: "Indicador se o sensor de temperatura do veículo não estava em funcionamento conforme especificação da SMTR"
      - name: indicadores.indicador_validador_sbd
        description: "Indicador se o veículo se encontra com o novo validador do Sistema de Bilhetagem Digital (SBD) instalado"
      - name: status
        description: "Classificação, observados os demais parâmetros - Categorias:\n
                      - Não licenciado - Veículo que operou, mas não é licenciado\n
                      - Autuado por ar inoperante - Veículo que operou, foi licenciado com ar condicionado e foi autuado por inoperância ou mau funcionamento do sistema de ar condicionado (023.II)\n
                      - Autuado por segurança - Veículo que operou, foi licenciado, mas foi autuado por infração relacionada à segurança do veículo\n
                      - Autuado por limpeza/equipamento - Veículo que operou, foi licenciado, mas foi autuado cumulativamente por infrações relacionadas à limpeza e equipamentos do veículo\n
                      - Sem ar e não autuado - Veículo que operou, foi licenciado sem ar condicionado e não foi autuado\n
                      - Com ar e não autuado - Veículo que operou, foi licenciado com ar condicionado e não foi autuado"
        tests:
          - not_null:
              name: not_null__status__sppo_veiculo_dia
      - name: datetime_ultima_atualizacao
        description: "{{ doc('datetime_ultima_atualizacao') }}"
      - name: data_licenciamento
        description: "Data do arquivo de licenciamento utilizado"
      - name: data_infracao
        description: "Data do arquivo de infrações utilizado"
      - name: tecnologia
        description: "{{ doc('tecnologia') }}"
      - name: versao
        description: "{{ doc('versao') }}"
  - name: sppo_registro_agente_verao
    description: "Tabela com registros de Agentes de Verão para fins de cálculo de subsídio nos termos da RESOLUÇÃO SMTR Nº 3.682/2024"
    columns:
      - name: data
        description: "Data de registro pelo agente público"
      - name: datetime_registro
        description: "Datetime de registro pelo agente público"
      - name: id_registro
        description: "ID do registro (HASH SHA256)"
      - name: id_veiculo
        description: "{{ doc('id_veiculo') }}"
      - name: servico
        description: "{{ doc('servico') }}"
      - name: link_foto
        description: "Link com a imagem interna do veículo"
      - name: validacao
        description: "Coluna de validação do registro enviado pelo agente público (apenas TRUE nesta tabela)"
      - name: datetime_captura
        description: "Datetime de captura do registro pela pipeline"
      - name: versao
        description: "{{ doc('versao') }}"