version: 2

models:
  - name: rho_registros_sppo
    description: "Tabela materializada para acesso geral aos dados do RHO SPPO"
    columns:
      - name: data_transacao
        description: "Data da transação (partição)"
      - name: hora_transacao
        description: "Hora da transação"
      - name: data_processamento
        description: "Data de processamento da transação"
      - name: data_arquivo_rho
        description: "Data do arquivo fonte do RHO"
      - name: servico_riocard
        description: "Nome curto da linha de acordo com o padrão do RioCard"
      - name: linha_riocard
        description: "Identificador interno da linha no RioCard"
      - name: operadora
        description: "Identificador da operadora de transporte"
      - name: quantidade_transacao_cartao
        description: "Quantidade de transações feitas com o cartão"
      - name: quantidade_transacao_especie
        description: "Quantidade de transações feitas em espécie"
      - name: quantidade_transacao_gratuidade
        description: "Quantidade de gratuidades"
      - name: registro_processado
        description: "Identificador se o registro foi recalculado"
      - name: datetime_captura
        description: "Data e hora da captura dos dados"

  - name: rho_registros_stpl
    description: "Tabela materializada para acesso geral aos dados do RHO STPL"
    columns:
      - name: data_transacao
        description: "Data da transação (partição)"
      - name: hora_transacao
        description: "Hora da transação"
      - name: servico_riocard
        description: "Nome curto da linha de acordo com o padrão do RioCard"
      - name: operadora
        description: "Identificador da operadora de transporte"
      - name: quantidade_transacao_pagante
        description: "Quantidade de transações pagantes"
      - name: quantidade_transacao_gratuidade
        description: "Quantidade de gratuidades"
      - name: arquivos_somados
        description: "Coluna de controle com array das datas dos arquivos que foram somados para obter os valores finais"
  - name: rdo40_registros
    description: "View para os dados do Resumo Diário de Operação com a quantidade total de passageiros."
    columns:
    - name: data
      description: "Data das transações"
    - name: ano
      description: "Ano das transações"
    - name: mes
      description: "Mês das transações"
    - name: dia
      description: "Dia das transações"
    - name: id_consorcio
      description: "Identificador do consórcio na tabela cadastro.consorcios"
    - name: consorcio
      description: "{{ doc('consorcio') }}"
    - name: servico
      description: "{{ doc('servico') }}"
    - name: linha
      description: "{{ doc('linha') }}"
    - name: tipo_servico
      description: "{{ doc('tipo_servico') }}"
    - name: ordem_servico
      description: "{{ doc('ordem_servico') }}"
    - name: codigo_veiculo
      description: "{{ doc('codigo_veiculo') }}"
    - name: tarifa_codigo
      description: "{{ doc('tarifa_codigo') }}"
    - name: tarifa_valor
      description: "{{ doc('tarifa_valor') }}"
    - name: frota_determinada
      description: "{{ doc('frota_determinada') }}"
    - name: frota_licenciada
      description: "{{ doc('frota_licenciada') }}"
    - name: frota_operante
      description: "{{ doc('frota_operante') }}"
    - name: qtd_viagens
      description: "{{ doc('qtd_viagens') }}"
    - name: qtd_km_cobertos
      description: "{{ doc('qtd_km_cobertos') }}"
    - name: qtd_grt_idoso
      description: "{{ doc('qtd_grt_idoso') }}"
    - name: qtd_grt_especial
      description: "{{ doc('qtd_grt_especial') }}"
    - name: qtd_grt_estud_federal
      description: "{{ doc('qtd_grt_estud_federal') }}"
    - name: qtd_grt_estud_estadual
      description: "{{ doc('qtd_grt_estud_estadual') }}"
    - name: qtd_grt_estud_municipal
      description: "{{ doc('qtd_grt_estud_municipal') }}"
    - name: qtd_grt_rodoviario
      description: "{{ doc('qtd_grt_rodoviario') }}"
    - name: qtd_buc_1_perna
      description: "{{ doc('qtd_buc_1_perna') }}"
    - name: qtd_buc_2_perna_integracao
      description: "{{ doc('qtd_buc_2_perna_integracao') }}"
    - name: receita_buc
      description: "{{ doc('receita_buc') }}"
    - name: qtd_buc_supervia_1_perna
      description: "{{ doc('qtd_buc_supervia_1_perna') }}"
    - name: qtd_buc_supervia_2_perna_integracao
      description: "{{ doc('qtd_buc_supervia_2_perna_integracao') }}"
    - name: receita_buc_supervia
      description: "{{ doc('receita_buc_supervia') }}"
    - name: qtd_cartoes_perna_unica_e_demais
      description: "{{ doc('qtd_cartoes_perna_unica_e_demais') }}"
    - name: receita_cartoes_perna_unica_e_demais
      description: "{{ doc('receita_cartoes_perna_unica_e_demais') }}"
    - name: qtd_pagamentos_especie
      description: "{{ doc('qtd_pagamentos_especie') }}"
    - name: receita_especie
      description: "{{ doc('receita_especie') }}"
    - name: qtd_grt_passe_livre_universitario
      description: "{{ doc('qtd_grt_passe_livre_universitario') }}"
    - name: class_servico
      description: "{{ doc('class_servico') }}"
    - name: qtd_passageiros_total
      description: "{{ doc('qtd_passageiros_total') }}"