[tool.poetry]
name = "pipelines"
version = "0.1.0"
description = ""
authors = ["Gabriel Gazola Milan <gabriel.gazola@poli.ufrj.br>"]

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
dbt-bigquery = "1.7.3"
google-cloud-storage = "2.13.0"
prefect = "1.4.1"
prefeitura-rio = "1.1.3a1"
basedosdados = "2.0.0b13"
agate = "1.7.1"
attrs = "23.1.0"
babel = "2.14.0"
backoff = "2.2.1"
cachetools = "5.3.2"
certifi = "2023.11.17"
cffi = "1.16.0"
charset-normalizer = "3.3.2"
click = "8.1.7"
cloudpickle = "3.0.0"
colorama = "0.4.6"
croniter = "2.0.1"
dask = "2023.12.0"
db-dtypes = "1.2.0"
dbt-core = "1.7.3"
dbt-extractor = "0.5.1"
dbt-semantic-interfaces = "0.4.2"
distributed = "2023.12.0"
docker = "7.0.0"
fsspec = "2023.12.2"
google-api-core = "2.15.0"
google-api-python-client = "2.110.0"
google-auth = "2.25.2"
google-auth-httplib2 = "0.2.0"
google-auth-oauthlib = "1.2.0"
google-cloud-bigquery = "3.14.0"
google-cloud-bigquery-connection = "1.14.0"
google-cloud-bigquery-storage = "2.23.0"
google-cloud-core = "2.4.1"
google-cloud-dataproc = "5.8.0"
google-crc32c = "1.5.0"
google-resumable-media = "2.6.0"
googleapis-common-protos = "1.62.0"
gql = "3.4.1"
graphql-core = "3.2.3"
grpc-google-iam-v1 = "0.13.0"
grpcio = "1.60.0"
grpcio-status = "1.60.0"
httplib2 = "0.22.0"
idna = "3.6"
importlib-metadata = "6.11.0"
importlib-resources = "6.1.1"
infisical = "1.5.0"
isodate = "0.6.1"
jinja2 = "3.1.2"
jsonschema = "4.20.0"
jsonschema-specifications = "2023.11.2"
leather = "0.3.4"
locket = "1.0.0"
logbook = "1.5.3"
loguru = "0.7.0"
markupsafe = "2.1.3"
marshmallow = "3.20.1"
marshmallow-oneofschema = "3.0.1"
mashumaro = "3.11"
minimal-snowplow-tracker = "0.0.2"
more-itertools = "10.1.0"
msgpack = "1.0.7"
multidict = "6.0.4"
mypy-extensions = "1.0.0"
networkx = "3.2.1"
numpy = "1.26.2"
oauthlib = "3.2.2"
packaging = "^24.0"
pandas = "2.1.4"
pandas-gbq = "0.19.2"
parsedatetime = "2.6"
partd = "1.4.1"
pathspec = "0.11.2"
pendulum = "2.1.2"
proto-plus = "1.23.0"
protobuf = "4.25.1"
psutil = "5.9.6"
pyarrow = "14.0.1"
pyasn1 = "0.5.1"
pyasn1-modules = "0.3.0"
pycparser = "2.21"
pycryptodomex = "3.19.0"
pydantic = "1.10.13"
pydata-google-auth = "1.8.2"
pynacl = "1.5.0"
pyparsing = "3.1.1"
python-box = "7.1.1"
python-dateutil = "2.8.2"
python-slugify = "8.0.1"
pytimeparse = "1.1.8"
pytz = "2023.3.post1"
pytzdata = "2020.1"
pyyaml = "6.0.1"
referencing = "0.32.0"
requests = "2.31.0"
requests-oauthlib = "1.3.1"
requests-toolbelt = "1.0.0"
rpds-py = "0.13.2"
rsa = "4.9"
sentry-sdk = "1.39.0"
six = "1.16.0"
sortedcontainers = "2.4.0"
sqlparse = "0.4.4"
tabulate = "0.9.0"
tblib = "3.0.0"
text-unidecode = "1.3"
toml = "0.10.2"
tomlkit = "0.11.8"
toolz = "0.12.0"
tornado = "6.4"
tqdm = "4.66.1"
typing-extensions = "4.9.0"
tzdata = "2023.3"
uritemplate = "4.1.1"
urllib3 = "1.26.18"
yarl = "1.9.4"
zict = "3.0.0"
zipp = "3.17.0"
pymysql = "^1.1.0"
psycopg2-binary = "^2.9.9"
redis-pal = "^1.0.0"
sqlalchemy = "^2.0.25"
google-cloud-dataplex = "^1.12.3"
openpyxl = "^3.1.4"
unidecode = "^1.3.8"


[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
black = "^23.7.0"
flake8 = "^6.1.0"
pre-commit = "^3.3.3"
taskipy = "^1.12.0"
isort = "^5.12.0"


[tool.poetry.group.ci]
optional = true

[tool.poetry.group.ci.dependencies]
networkx = "^3.1"
loguru = "^0.7.0"
typer = "^0.9.0"

[tool.poetry.group.extras.dependencies]
jaydebeapi = "1.2.3"

[tool.black]
line-length = 100
target-version = ["py310"]
include = "\\.pyi?$"

[tool.isort]
profile = "black"

[tool.taskipy.tasks]
lint = "black . && isort . && flake8 ."

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"