version: 2

models:
  - name: gps_brt_datario
    description: "Dados tratados de registros de GPS do BRT"
    columns:
      - name: modo
        description: "{{ doc('modo_brt') }}"
      - name: timestamp_gps
        description: "{{ doc('timestamp_gps') }}"
      - name: data
        description: "{{ doc('data_gps') }}"
      - name: hora
        description: "{{ doc('hora_gps') }}"
      - name: id_veiculo
        description: "{{ doc('id_veiculo') }}"
      - name: servico
        description: "{{ doc('servico') }}"
      - name: latitude
        description: "{{ doc('latitude_gps') }}"
      - name: longitude
        description: "{{ doc('longitude_gps') }}"
      - name: flag_em_movimento
        description: "{{ doc('flag_em_movimento') }}"
      - name: tipo_parada
        description: "{{ doc('tipo_parada') }}"
      - name: flag_linha_existe_sigmob
        description: "{{ doc('flag_linha_existe_sigmob') }}"
      - name: velocidade_instantanea
        description: "{{ doc('velocidade_instantanea') }}"
      - name: velocidade_estimada_10_min
        description: "{{ doc('velocidade_estimada_10_min') }}"
      - name: distancia
        description: "{{ doc('distancia_gps') }}"
      - name: versao
        description: "{{ doc('versao') }}"

  - name: gps_onibus_datario
    description: "Dados tratados de registros de GPS dos Ônibus"
    columns:
      - name: modo
        description: "{{ doc('modo_sppo') }}"
      - name: timestamp_gps
        description: "{{ doc('timestamp_gps') }}"
      - name: data
        description: "{{ doc('data_gps') }}"
      - name: hora
        description: "{{ doc('hora_gps') }}"
      - name: id_veiculo
        description: "{{ doc('id_veiculo') }}"
      - name: servico
        description: "{{ doc('servico') }}"
      - name: latitude
        description: "{{ doc('latitude_gps') }}"
      - name: longitude
        description: "{{ doc('longitude_gps') }}"
      - name: flag_em_movimento
        description: "{{ doc('flag_em_movimento') }}"
      - name: tipo_parada
        description: "{{ doc('tipo_parada') }}"
      - name: flag_linha_existe_sigmob
        description: "{{ doc('flag_linha_existe_sigmob') }}"
      - name: velocidade_instantanea
        description: "{{ doc('velocidade_instantanea') }}"
      - name: velocidade_estimada_10_min
        description: "{{ doc('velocidade_estimada_10_min') }}"
      - name: distancia
        description: "{{ doc('distancia_gps') }}"
      - name: fonte_gps
        description: "Fornecedor dos dados de GPS (zirix ou conecta)"
      - name: versao
        description: "{{ doc('versao') }}"
  - name: viagem_onibus_datario
    description: "Detalhes de todas as viagens completas identificadas"
    columns:
      - name: data
        description: "{{ doc('data_viagem') }}"
      - name: consorcio
        description: "Consórcio ao qual o serviço pertence"
      - name: tipo_dia
        description: "Dia da semana considerado para o cálculo da distância planejada - categorias: Dia Útil, Sábado, Domingo"
      - name: id_empresa
        description: "{{ doc('id_empresa') }}"
      - name: id_veiculo
        description: "{{ doc('id_veiculo') }}"
      - name: id_viagem
        description: "Código identificador da viagem (ex: id_veiculo + servico + sentido + shape_id + datetime_partida)"
      - name: servico
        description: "Serviço realizado pelo veículo (com base na identificação do trajeto)"
      - name: shape_id
        description: "{{ doc('shape_id') }}"
      - name: sentido
        description: "{{ doc('sentido') }}"
      - name: datetime_partida
        description: "Horário de início da viagem"
      - name: datetime_chegada
        description: "Horário de fim da viagem"
      - name: tempo_viagem
        description: "{{ doc('tempo_viagem') }}"
      - name: distancia_planejada
        description: "{{ doc('distancia_planejada') }}"
      - name: perc_conformidade_shape
        description: "{{ doc('perc_conformidade_shape') }}"
      - name: perc_conformidade_registros
        description: "{{ doc('perc_conformidade_registros') }}"
      - name: versao_modelo
        description: "{{ doc('versao') }}"

  - name: licenciamento_veiculo_datario
    description: "Tabela histórica de dados cadastrais dos veículos que operam o sistema de transporte rodoviário,
                  considerando tanto os licenciados no Sistema de Transporte Urbano [STU] quanto as solicitações
                  válidas em andamento para ingresso no sistema"
    columns:
      - name: data
        description: "{{ doc('data_captura') }} [partição]"
      - name: modo
        description: "{{ doc('modo') }}"
      - name: id_veiculo
        description: "{{ doc('id_veiculo') }}"
      - name: ano_fabricacao
        description: "{{ doc('ano_fabricacao') }}"
      - name: carroceria
        description: "{{ doc('carroceria') }}"
      - name: data_ultima_vistoria
        description: "{{ doc('data_ultima_vistoria') }}"
      - name: id_carroceria
        description: "{{ doc('id_carroceria') }}"
      - name: id_chassi
        description: "{{ doc('id_chassi') }}"
      - name: id_fabricante_chassi
        description: "{{ doc('id_fabricante_chassi') }}"
      - name: id_interno_carroceria
        description: "{{ doc('id_interno_carroceria') }}"
      - name: id_planta
        description: "{{ doc('id_planta') }}"
      - name: indicador_ar_condicionado
        description: "{{ doc('indicador_ar_condicionado') }}"
      - name: indicador_elevador
        description: "{{ doc('indicador_elevador') }}"
      - name: indicador_usb
        description: "{{ doc('indicador_usb') }}"
      - name: indicador_wifi
        description: "{{ doc('indicador_wifi') }}"
      - name: nome_chassi
        description: "{{ doc('nome_chassi') }}"
      - name: permissao
        description: "{{ doc('permissao') }}"
      - name: placa
        description: "{{ doc('placa') }}"
      - name: quantidade_lotacao_pe
        description: "{{ doc('quantidade_lotacao_pe') }}"
      - name: quantidade_lotacao_sentado
        description: "{{ doc('quantidade_lotacao_sentado') }}"
      - name: tipo_combustivel
        description: "{{ doc('tipo_combustivel') }}"
      - name: tipo_veiculo
        description: "{{ doc('tipo_veiculo') }}"
      - name: tecnologia
        description: "{{ doc('tecnologia') }}"
      - name: status
        description: "{{ doc('status') }}"
      - name: ano_ultima_vistoria_atualizado
        description: "{{ doc('ano_ultima_vistoria_atualizado') }}"
      - name: data_inicio_vinculo
        description: "{{ doc('data_inicio_vinculo') }}"
      - name: datetime_ultima_atualizacao
        description: "{{ doc('datetime_ultima_atualizacao') }}"
      - name: versao
        description: "{{ doc('versao') }}"