models:
  - name: viagem_informada_monitoramento
    description: "Detalhes das viagens informadas pelas operadoras de ônibus"
    columns:
      - name: data
        description: "{{ doc('data_viagem') }} [partição]"
        data_type: date
        quote: true
      - name: id_viagem
        description: "{{ doc('id_viagem') }}"
        data_type: string
        quote: true
      - name: datetime_partida
        description: "{{ doc('datetime_partida') }}"
        data_type: datetime
        quote: true
      - name: datetime_chegada
        description: "{{ doc('datetime_chegada') }}"
        data_type: datetime
        quote: true
      - name: modo
        description: "{{ doc('modo') }}"
        data_type: string
        quote: true
      - name: id_veiculo
        description: "{{ doc('id_veiculo') }}"
        data_type: string
        quote: true
      - name: trip_id
        description: "{{ doc('trip_id') }}"
        data_type: int64
        quote: true
      - name: route_id
        description: "{{ doc('route_id') }}"
        data_type: string
        quote: true
      - name: shape_id
        description: Identificador de um shape da tabela shapes do GTFS
        data_type: string
        quote: true
      - name: servico
        description: "{{ doc('servico') }}"
        data_type: string
        quote: true
      - name: sentido
        description: "{{ doc('sentido') }}"
        data_type: string
        quote: true
      - name: fonte_gps
        description: Fornecedor de dados de GPS a ser considerado para validar a viagem
        data_type: string
        quote: true
      - name: datetime_processamento
        description: Data e hora do processamento da viagem [GMT-3]
        data_type: datetime
        quote: true
      - name: datetime_captura
        description: Data e hora da captura da integração [GMT-3]
        data_type: string
        quote: true
      - name: versao
        description: "{{ doc('versao') }}"
        data_type: string
        quote: true
      - name: datetime_ultima_atualizacao
        description: "{{ doc('datetime_ultima_atualizacao') }}"
        data_type: datetime
        quote: true
  - name: viagem_validacao
    description: "Tabela que informa se a viagem informada está ou não válida de acordo com os parâmetros definidos"
    columns:
      - name: data
        description: "{{ doc('data_viagem') }} [partição]"
        data_type: date
        quote: true
      - name: id_viagem
        description: "{{ doc('id_viagem') }}"
        data_type: string
        quote: true
      - name: datetime_partida
        description: "{{ doc('datetime_partida') }}"
        data_type: datetime
        quote: true
      - name: datetime_chegada
        description: "{{ doc('datetime_chegada') }}"
        data_type: datetime
        quote: true
      - name: modo
        description: "{{ doc('modo') }}"
        data_type: string
        quote: true
      - name: id_veiculo
        description: "{{ doc('id_veiculo') }}"
        data_type: string
        quote: true
      - name: trip_id
        description: "{{ doc('trip_id') }}"
        data_type: int64
        quote: true
      - name: route_id
        description: "{{ doc('route_id') }}"
        data_type: string
        quote: true
      - name: shape_id
        description: "Identificador de um shape da tabela shapes do GTFS"
        data_type: string
        quote: true
      - name: servico
        description: "{{ doc('servico') }}"
        data_type: string
        quote: true
      - name: sentido
        description: "{{ doc('sentido') }}"
        data_type: string
        quote: true
      - name: distancia_planejada
        description: "{{ doc('distancia_planejada') }}"
        data_type: float64
        quote: true
      - name: velocidade_media
        description: "Velocidade média da viagem (km/h)"
        data_type: float64
        quote: true
      - name: quantidade_segmentos_verificados
        description: "Quantidade de segmentos considerados na validação"
        data_type: int64
        quote: true
      - name: quantidade_segmentos_validos
        description: "Quantidade de segmentos com pelo menos um sinal de GPS"
        data_type: int64
        quote: true
      - name: quantidade_segmentos_necessarios
        description: "Quantidade mínima de segmentos para que a viagem seja validada"
        data_type: int64
        quote: true
      - name: indicador_viagem_sobreposta
        description: "Indica se a viagem se sobrepõe a outra viagem do mesmo veículo"
        data_type: boolean
        quote: true
      - name: indicador_trajeto_valido
        description: "Indica se o veículo cumpriu o trajeto [quantidade_segmentos_validos >= quantidade_segmentos_necessarios]"
        data_type: boolean
        quote: true
      - name: indicador_servico_planejado_gtfs
        description: "Indica se o serviço estava planejado para o tipo dia no GTFS"
        data_type: boolean
        quote: true
      - name: indicador_servico_planejado_os
        description: "Indica se o serviço estava planejado para a faixa horária na OS [apenas para SPPO]"
        data_type: boolean
        quote: true
      - name: indicador_servico_divergente
        description: "{{ doc('indicador_servico_divergente') }}"
        data_type: boolean
        quote: true
      - name: indicador_shape_invalido
        description: "Indica se o shape existe no GTFS no feed vigente durante a data da viagem"
        data_type: boolean
        quote: true
      - name: indicador_trajeto_alternativo
        description: "Indica se o shape é um trajeto alternativo"
        data_type: boolean
        quote: true
      - name: indicador_acima_velocidade_max
        description: "Indica se a velocidade média da viagem está acima do limite estabelecido"
        data_type: boolean
        quote: true
      - name: indicador_viagem_valida
        description: "Indica se a viagem está válida conforme critérios definidos"
        data_type: boolean
        quote: true
      - name: tipo_dia
        description: "{{ doc('tipo_dia') }}"
        data_type: string
        quote: true
      - name: feed_version
        description: "{{ doc('feed_version') }}"
        data_type: string
        quote: true
      - name: feed_start_date
        description: "{{ doc('feed_start_date') }}"
        data_type: date
        quote: true
      - name: versao
        description: "{{ doc('versao') }}"
        data_type: string
        quote: true
      - name: datetime_ultima_atualizacao
        description: "{{ doc('datetime_ultima_atualizacao') }}"
        data_type: datetime
        quote: true

  - name: gps_segmento_viagem
    description: "Segmentos de viagem associados a sinais de GPS"
    columns:
      - name: data
        description: "Data da viagem [partição]"
        data_type: date
        quote: true
      - name: id_viagem
        description: "{{ doc('id_viagem') }}"
        data_type: string
        quote: true
      - name: datetime_partida
        description: "{{ doc('datetime_partida') }}"
        data_type: datetime
        quote: true
      - name: datetime_chegada
        description: "{{ doc('datetime_chegada') }}"
        data_type: datetime
        quote: true
      - name: modo
        description: "{{ doc('modo') }}"
        data_type: string
        quote: true
      - name: id_veiculo
        description: "{{ doc('id_veiculo') }}"
        data_type: string
        quote: true
      - name: trip_id
        description: "{{ doc('trip_id') }}"
        data_type: int64
        quote: true
      - name: route_id
        description: "{{ doc('route_id') }}"
        data_type: string
        quote: true
      - name: shape_id
        description: "Identificador de um shape da tabela shapes do GTFS"
        data_type: string
        quote: true
      - name: id_segmento
        description: "Identificador do segmento do shape"
        data_type: string
        quote: true
      - name: servico
        description: "{{ doc('servico') }}"
        data_type: string
        quote: true
      - name: sentido
        description: "{{ doc('sentido') }}"
        data_type: string
        quote: true
      - name: quantidade_gps
        description: "Quantidade de sinais GPS detectados no segmento"
        data_type: int64
        quote: true
      - name: indicador_viagem_sobreposta
        description: "Indica se a viagem se sobrepõe a outra viagem do mesmo veículo"
        data_type: boolean
        quote: true
      - name: indicador_segmento_desconsiderado
        description: "Indica se o segmento deve ser desconsiderado na validação"
        data_type: boolean
        quote: true
      - name: indicador_servico_divergente
        description: "{{ doc('indicador_servico_divergente') }}"
        data_type: boolean
        quote: true
      - name: feed_version
        description: "{{ doc('feed_version') }}"
        data_type: string
        quote: true
      - name: feed_start_date
        description: "{{ doc('feed_start_date') }}"
        data_type: date
        quote: true
      - name: service_ids
        description: Identifica um conjunto de datas em que o serviço está disponível para uma ou mais rotas no GTFS
        data_type: array
        quote: true
      - name: tipo_dia
        description: "{{ doc('tipo_dia') }}"
        data_type: string
        quote: true
      - name: versao
        description: "{{ doc('versao') }}"
        data_type: string
        quote: true
      - name: datetime_ultima_atualizacao
        description: "{{ doc('datetime_ultima_atualizacao') }}"
        data_type: datetime
        quote: true

  - name: gps
    description: "Tabela com os dados tratados de registros de GPS da API {{ var('fonte_gps') }}, incluindo velocidade estimada, estado de movimento, parada em terminal ou garagem e interseção com o traçado da linha informada"
    columns:
      - name: data
        description: "{{ doc('data_gps') }}"
      - name: hora
        description: "{{ doc('hora_gps') }}"
      - name: datetime_gps
        description: "{{ doc('timestamp_gps') }}"
      - name: id_veiculo
        description: "{{ doc('id_veiculo') }}"
      - name: servico
        description: "{{ doc('servico') }}"
      - name: latitude
        description: "{{ doc('latitude_gps') }}"
      - name: longitude
        description: "{{ doc('longitude_gps') }}"
      - name: status
        description: "{{ doc('status_veiculo_gps') }}"
      - name: velocidade_instantanea
        description: "{{ doc('velocidade_instantanea') }}"
      - name: velocidade_estimada_10_min
        description: "{{ doc('velocidade_estimada_10_min') }}"
      - name: distancia
        description: "{{ doc('distancia_gps') }}"
      - name: versao
        description: "{{ doc('versao') }}"
      - name: datetime_ultima_atualizacao
        description: "{{ doc('datetime_ultima_atualizacao') }}"

  - name: gps_15_minutos
    description: "Tabela com os dados tratados de registros de GPS da API {{ var('fonte_gps') }}, incluindo velocidade estimada, estado de movimento, parada em terminal ou garagem e interseção com o traçado da linha informada"
    columns:
      - name: data
        description: "{{ doc('data_gps') }}"
      - name: hora
        description: "{{ doc('hora_gps') }}"
      - name: datetime_gps
        description: "{{ doc('timestamp_gps') }}"
      - name: id_veiculo
        description: "{{ doc('id_veiculo') }}"
      - name: servico
        description: "{{ doc('servico') }}"
      - name: latitude
        description: "{{ doc('latitude_gps') }}"
      - name: longitude
        description: "{{ doc('longitude_gps') }}"
      - name: status
        description: "{{ doc('status_veiculo_gps') }}"
      - name: velocidade_instantanea
        description: "{{ doc('velocidade_instantanea') }}"
      - name: velocidade_estimada_10_min
        description: "{{ doc('velocidade_estimada_10_min') }}"
      - name: distancia
        description: "{{ doc('distancia_gps') }}"
      - name: versao
        description: "{{ doc('versao') }}"
      - name: datetime_ultima_atualizacao
        description: "{{ doc('datetime_ultima_atualizacao') }}"
  - name: veiculo_fiscalizacao_lacre
    description: Tabela com as informações do controle do lacre e deslacre de veículos
    columns:
      - name: id_veiculo
        description: "{{ doc('id_veiculo') }}"
        data_type: string
        quote: true
      - name: placa
        description: "{{ doc('placa') }}"
        data_type: string
        quote: true
      - name: data_inicio_lacre
        description: Data de inicio do lacre [partição]
        data_type: date
        quote: true
      - name: data_fim_lacre
        description: Data de fim do lacre
        data_type: date
        quote: true
      - name: id_consorcio
        description: "{{ doc('id_consorcio') }}"
        data_type: string
        quote: true
      - name: consorcio
        description: "{{ doc('consorcio') }}"
        data_type: string
        quote: true
      - name: id_auto_infracao
        description: "{{ doc('id_auto_infracao') }}"
        tests:
          - dbt_utils.relationships_where:
              name: dbt_utils.relationships_where__id_auto_infracao__veiculo_fiscalizacao_lacre
              to: ref('autuacao_disciplinar_historico')
              field: id_auto_infracao
        data_type: string
        quote: true
      - name: datetime_ultima_atualizacao_fonte
        description: Datetime da última atualização da informação na fonte dos dados [GMT-3]
        data_type: datetime
        quote: true
      - name: datetime_ultima_atualizacao
        description: "{{ doc('datetime_ultima_atualizacao') }}"
        data_type: datetime
        quote: true
      - name: versao
        description: "{{ doc('versao') }}"
        data_type: string
        quote: true
  - name: autuacao_disciplinar_historico
    description: Tabela histórica de todas as multas aplicadas aos modos de transporte no município do Rio de Janeiro
    columns:
      - name: data
        description: "{{ doc('data_infracao') }} [partição]"
        data_type: date
        quote: true
      - name: id_auto_infracao
        description: "{{ doc('id_auto_infracao') }}"
        data_type: string
        quote: true
      - name: id_infracao
        description: "{{ doc('id_infracao') }}"
        data_type: string
        quote: true
      - name: modo
        description: "{{ doc('modo_onibus') }}"
        data_type: string
        quote: true
      - name: servico
        description: "{{ doc('servico') }}"
        data_type: string
        quote: true
      - name: permissao
        description: "{{ doc('permissao') }}"
        data_type: string
        quote: true
      - name: placa
        description: "{{ doc('placa') }}"
        data_type: string
        quote: true
      - name: valor
        description: "{{ doc('valor') }}"
        data_type: float64
        quote: true
      - name: data_pagamento
        description: "{{ doc('data_pagamento') }}"
        data_type: date
        quote: true
      - name: data_inclusao
        description: Data de inclusão da autuação no arquivo enviado pelo STU
        data_type: date
        quote: true
      - name: versao
        description: "{{ doc('versao') }}"
        data_type: string
        quote: true
      - name: datetime_ultima_atualizacao
        description: "{{ doc('datetime_ultima_atualizacao') }}"
        data_type: datetime
        quote: true
  - name: veiculo_dia
    description: Tabela resumo dos veículos e seus respectivos indicadores
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
          - data
          - id_veiculo
          name: dbt_utils.unique_combination_of_columns__data_id_veiculo__veiculo_dia
      - dbt_expectations.expect_row_values_to_have_data_for_every_n_datepart:
          date_col: data
          row_condition: "1=1"
          test_start_date: "{{ var('date_range_start') }}"
          test_end_date: "{{ modules.datetime.datetime.fromisoformat(var('date_range_end')) + modules.datetime.timedelta(1) }}"
          name: dbt_expectations.expect_row_values_to_have_data_for_every_n_datepart__veiculo_dia
    columns:
      - name: data
        description: "{{ doc('data_operacao') }}"
        data_type: date
        quote: true
      - name: id_veiculo
        description: "{{ doc('id_veiculo') }}"
        tests:
          - not_null:
              name: not_null__id_veiculo__veiculo_dia
        data_type: string
        quote: true
      - name: placa
        description: "{{ doc('placa') }}"
        data_type: string
        quote: true
      - name: modo
        description: "{{ doc('modo') }}"
        data_type: string
        quote: true
      - name: tecnologia
        description: "{{ doc('tecnologia') }}"
        data_type: string
        quote: true
      - name: status
        description: "{{ doc('status_veiculo') }}"
        tests:
          - not_null:
              name: not_null__status__sppo_veiculo_dia
        data_type: string
        quote: true
      - name: indicadores
        description: "{{ doc('indicadores_veiculo') }}"
        data_type: json
        quote: true
      - name: datetime_ultima_atualizacao
        description: "{{ doc('datetime_ultima_atualizacao') }}"
        data_type: datetime
        quote: true
      - name: versao
        description: "{{ doc('versao') }}"
        data_type: string
        quote: true
