version: 2

models:
  - name: subsidio_faixa_servico_dia_tipo_viagem
    description: "Sumário do subsídio dos serviços de ônibus [SPPO] por dia, faixa horária e tipo de viagem"
    columns:
      - name: data
        description: "{{ doc('data_gps') }}"
      - name: tipo_dia
        description: "Dia da semana considerado para o cálculo da distância planejada - categorias: Dia Útil, Sabado, Domingo"
      - name: faixa_horaria_inicio
        description: "{{ doc('faixa_horaria_inicio') }}"
      - name: faixa_horaria_fim
        description: "{{ doc('faixa_horaria_fim') }}"
      - name: consorcio
        description: "{{ doc('consorcio') }}"
      - name: servico
        description: "{{ doc('servico') }}"
      - name: indicador_ar_condicionado
        description: "{{ doc('indicador_ar_condicionado') }}"
      - name: indicador_penalidade_judicial
        description: "{{ doc('indicador_penalidade_judicial') }}"
      - name: indicador_viagem_dentro_limite
        description: "{{ doc('indicador_viagem_dentro_limite') }}"
      - name: tipo_viagem
        description: "{{ doc('tipo_viagem_status') }}"
      - name: tecnologia_apurada
        description: "{{ doc('tecnologia') }}"
      - name: tecnologia_remunerada
        description: "{{ doc('tecnologia_remunerada') }}"
      - name: viagens_faixa
        description: "{{ doc('viagens_faixa') }}"
      - name: km_apurada_faixa
        description: "{{ doc('km_apurada_faixa') }}"
      - name: km_subsidiada_faixa
        description: "Distância subsidiada para o serviço por faixa horária (km)"
      - name: valor_apurado
        description: "Valor da distância apurada multiplicada pelo subsídio por quilômetro [sem glosa, é zerado quando POF < 80%]"
      - name: valor_glosado_tecnologia
        description: "{{ doc('valor_glosado_tecnologia') }}"
      - name: valor_acima_limite
        description: "{{ doc('valor_acima_limite') }}"
      - name: valor_total_sem_glosa
        description: "{{ doc('valor_total_sem_glosa') }}"
      - name: versao
        description: "{{ doc('versao') }}"
      - name: datetime_ultima_atualizacao
        description: "{{ doc('datetime_ultima_atualizacao') }}"
      - name: id_execucao_dbt
        description: "{{ doc('id_execucao_dbt') }}"
      - name: sentido
        description: "{{ doc('sentido') }}"
  - name: subsidio_sumario_servico_dia_pagamento
    description: "Sumário do subsídio dos serviços de ônibus [SPPO] por dia [Dados entre 2024-08-16 e 2025-01-05]"
    columns:
      - name: data
        description: "{{ doc('data_gps') }}"
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: "'2024-08-15'"
              max_value: "'{{ var('DATA_SUBSIDIO_V14_INICIO') }}'"
              strictly: true
              name: dbt_expectations.expect_column_values_to_be_between__data__subsidio_sumario_servico_dia_pagamento
      - name: tipo_dia
        description: "Dia da semana considerado para o cálculo da distância planejada - categorias: Dia Útil, Sabado, Domingo"
      - name: consorcio
        description: "Consórcio que opera o serviço"
      - name: servico
        description: "{{ doc('servico') }}"
      - name: viagens_dia
        description: "{{ doc('viagens_dia') }}"
      - name: km_apurada_dia
        description: "{{ doc('km_apurada') }}"
      - name: km_subsidiada_dia
        description: "{{ doc('km_subsidiada_dia') }}"
      - name: km_planejada_dia
        description: "{{ doc('km_planejada_dia') }}"
      - name: valor_a_pagar
        description: "{{ doc('valor_a_pagar') }}"
      - name: valor_glosado
        description: "{{ doc('valor_glosado') }}"
      - name: valor_acima_limite
        description: "{{ doc('valor_acima_limite') }}"
      - name: valor_total_sem_glosa
        description: "{{ doc('valor_total_sem_glosa') }}"
      - name: valor_total_apurado
        description: "{{ doc('valor_total_apurado') }}"
      - name: valor_judicial
        description: "{{ doc('valor_judicial') }}"
      - name: valor_penalidade
        description: "{{ doc('valor_penalidade') }}"
      - name: versao
        description: "{{ doc('versao') }}"
      - name: datetime_ultima_atualizacao
        description: "{{ doc('datetime_ultima_atualizacao') }}"
  - name: subsidio_penalidade_servico_faixa
    description: "Tabela com o valor penalidade dos serviços de ônibus [SPPO] por faixa horária e serviço"
    columns:
      - name: data
        description: "{{ doc('data_gps') }}"
      - name: tipo_dia
        description: "{{ doc('tipo_dia') }}"
      - name: consorcio
        description: "{{ doc('consorcio') }}"
      - name: servico
        description: "{{ doc('servico') }}"
      - name: faixa_horaria_inicio
        description: "{{ doc('faixa_horaria_inicio') }}"
      - name: faixa_horaria_fim
        description: "{{ doc('faixa_horaria_fim') }}"
      - name: valor_penalidade
        description: "{{ doc('valor_penalidade') }}"
      - name: versao
        description: "{{ doc('versao') }}"
      - name: datetime_ultima_atualizacao
        description: "{{ doc('datetime_ultima_atualizacao') }}"
      - name: id_execucao_dbt
        description: "{{ doc('id_execucao_dbt') }}"
      - name: sentido
        description: "{{ doc('sentido') }}"
  - name: bilhetagem_consorcio_dia
    description: "Tabela com os valores totais de pagamento da Jaé agregados por consorcio e dia"
    columns:
      - name: data_ordem
        description: "{{ doc('data_ordem') }} (partição)"
      - name: id_consorcio
        description: "{{ doc('id_consorcio') }}"
      - name: consorcio
        description: "{{ doc('nome_consorcio') }}"
      - name: id_ordem_pagamento
        description: "Identificador da ordem pagamento no banco de dados da Jaé"
      - name: quantidade_transacao_debito
        description: "Quantidade de transações feitas na modalidade débito"
      - name: valor_debito
        description: "Valor total das transações feitas na modalidade débito (R$)"
      - name: quantidade_transacao_especie
        description: "{{ doc('quantidade_transacao_especie') }}"
      - name: valor_especie
        description: "Valor total das transações feitas em espécie (R$)"
      - name: quantidade_transacao_gratuidade
        description: "Quantidade de transações feitas com gratuidade"
      - name: valor_gratuidade
        description: "Valor total das transações feitas com gratuidade (R$)"
      - name: quantidade_transacao_integracao
        description: "Quantidade de transações feitas com integração"
      - name: valor_integracao
        description: "Valor total das transações feitas com integração (R$)"
      - name: quantidade_transacao_rateio_credito
        description: "Quantidade total de transações consideradas no crédito da repartição tarifária"
      - name: valor_rateio_credito
        description: "Valor total creditado em decorrência da repartição tarifária (R$)"
      - name: quantidade_transacao_rateio_debito
        description: "Quantidade total de transações consideradas no débito da repartição tarifária"
      - name: valor_rateio_debito
        description: "Valor total debitado em decorrência da repartição tarifária (R$)"
      - name: quantidade_total_transacao
        description: "{{ doc('quantidade_total_transacao') }}"
      - name: valor_total_transacao_bruto
        description: "Valor total das transações realizadas (R$)"
      - name: valor_total_transacao_liquido
        description: "Valor total das transações menos o valor_desconto_taxa (R$)"
      - name: valor_desconto_taxa
        description: "Valor da taxa descontado do valor total (R$)"
      - name: versao
        description: "{{ doc('versao') }}"
  - name: bilhetagem_consorcio_operador_dia
    description: "Tabela com os valores totais de pagamento da Jaé agregados por consorcio, operador e dia"
    columns:
      - name: data_ordem
        description: "{{ doc('data_ordem') }} [partição]"
        tests:
          - dbt_expectations.expect_column_max_to_be_between:
              min_value: "current_date('America/Sao_Paulo')"
              strictly: false
              where: "1=1"
              name: dbt_expectations.expect_column_max_to_be_between__data_ordem__bilhetagem_consorcio_operador_dia

      - name: id_ordem_pagamento_consorcio_operador_dia
        description: "Identificador único do registro no banco de dados da Jaé"
        tests:
          - not_null:
              where: "data_ordem in ({partitions})"
              name: not_null__id_ordem_pagamento_consorcio_operador_dia__bilhetagem_consorcio_operador_dia
      - name: id_consorcio
        description: "{{ doc('id_consorcio') }}"
        tests:
          - not_null:
              where: "data_ordem in ({partitions})"
              name: not_null__id_consorcio__bilhetagem_consorcio_operador_dia
      - name: consorcio
        description: "{{ doc('nome_consorcio') }}"
        tests:
          - not_null:
              where: "data_ordem in ({partitions})"
              name: not_null__consorcio__bilhetagem_consorcio_operador_dia
      - name: id_operadora
        description: "{{ doc('id_operadora') }}"
        tests:
          - not_null:
              where: "data_ordem in ({partitions})"
              name: not_null__id_operadora__bilhetagem_consorcio_operador_dia
      - name: operadora
        description: "{{ doc('operadora') }}"
      - name: id_ordem_pagamento
        description: "Identificador da ordem pagamento no banco de dados da Jaé"
        tests:
          - not_null:
              where: "data_ordem in ({partitions})"
              name: not_null__id_ordem_pagamento__bilhetagem_consorcio_operador_dia
      - name: quantidade_transacao_debito
        description: "Quantidade de transações feitas na modalidade débito"
      - name: valor_debito
        description: "Valor total das transações feitas na modalidade débito (R$)"
      - name: quantidade_transacao_especie
        description: "{{ doc('quantidade_transacao_especie') }}"
      - name: valor_especie
        description: "Valor total das transações feitas em espécie (R$)"
      - name: quantidade_transacao_gratuidade
        description: "Quantidade de transações feitas com gratuidade"
      - name: valor_gratuidade
        description: "Valor total das transações feitas com gratuidade (R$)"
      - name: quantidade_transacao_integracao
        description: "Quantidade de transações feitas com integração"
      - name: valor_integracao
        description: "Valor total das transações feitas com integração (R$)"
      - name: quantidade_transacao_rateio_credito
        description: "Quantidade total de transações consideradas no crédito da repartição tarifária"
      - name: valor_rateio_credito
        description: "Valor total creditado em decorrência da repartição tarifária (R$)"
      - name: quantidade_transacao_rateio_debito
        description: "Quantidade total de transações consideradas no débito da repartição tarifária"
      - name: valor_rateio_debito
        description: "Valor total debitado em decorrência da repartição tarifária (R$)"
      - name: quantidade_total_transacao
        description: "{{ doc('quantidade_total_transacao') }}"
      - name: valor_total_transacao_bruto
        description: "Valor total das transações realizadas (R$)"
      - name: valor_desconto_taxa
        description: "Valor da taxa descontado do valor total (R$)"
      - name: valor_total_transacao_liquido_ordem
        description: "Valor total das transações menos o valor_desconto_taxa (R$)"
      - name: valor_total_transacao_liquido
        description: "Valor corrigido total das transações menos o valor_desconto_taxa (R$)"
      - name: data_pagamento
        description: "Data em que foi realizado o pagamento ao operador ou consórcio"
      - name: valor_pago
        description: "Valor pago ao operador ou consórcio (R$)"
      - name: datetime_captura
        description: "Data e hora da captura da ordem [GMT-3]"
      - name: versao
        description: "{{ doc('versao') }}"
      - name: datetime_ultima_atualizacao
        data_type: datetime
        quote: true
        description: "{{ doc('datetime_ultima_atualizacao') }}"
  - name: bilhetagem_dia
    description: "Tabela com os valores totais de pagamento da Jaé agregados por dia"
    columns:
      - name: data_ordem
        description: "{{ doc('data_ordem') }} (partição)"
      - name: data_pagamento
        description: "{{ doc('data_pagamento') }}"
      - name: id_ordem_pagamento
        description: "Identificador da ordem pagamento no banco de dados da Jaé"
      - name: quantidade_transacao_debito
        description: "Quantidade de transações feitas na modalidade débito"
      - name: valor_debito
        description: "Valor total das transações feitas na modalidade débito (R$)"
      - name: quantidade_transacao_especie
        description: "{{ doc('quantidade_transacao_especie') }}"
      - name: valor_especie
        description: "Valor total das transações feitas em espécie (R$)"
      - name: quantidade_transacao_gratuidade
        description: "Quantidade de transações feitas com gratuidade"
      - name: valor_gratuidade
        description: "Valor total das transações feitas com gratuidade (R$)"
      - name: quantidade_transacao_integracao
        description: "Quantidade de transações feitas com integração"
      - name: valor_integracao
        description: "Valor total das transações feitas com integração (R$)"
      - name: quantidade_transacao_rateio_credito
        description: "Quantidade total de transações consideradas no crédito da repartição tarifária"
      - name: valor_rateio_credito
        description: "Valor total creditado em decorrência da repartição tarifária (R$)"
      - name: quantidade_total_transacao
        description: "{{ doc('quantidade_total_transacao') }}"
      - name: quantidade_transacao_rateio_debito
        description: "Quantidade total de transações consideradas no débito da repartição tarifária"
      - name: valor_rateio_debito
        description: "Valor total debitado em decorrência da repartição tarifária (R$)"
      - name: valor_total_transacao_bruto
        description: "Valor total das transações realizadas (R$)"
      - name: valor_desconto_taxa
        description: "Valor da taxa descontado do valor total (R$)"
      - name: valor_total_transacao_liquido
        description: "Valor total das transações menos o valor_desconto_taxa (R$)"
      - name: versao
        description: "{{ doc('versao') }}"
  - name: bilhetagem_servico_operador_dia
    descriptions: "Tabela com os valores totais de pagamento da Jaé agregados por serviço, operador e dia"
    columns:
      - name: data_ordem
        description: "{{ doc('data_ordem') }} (partição)"
      - name: id_consorcio
        description: "{{ doc('id_consorcio') }}"
      - name: consorcio
        description: "{{ doc('consorcio') }}"
      - name: id_operadora
        description: "{{ doc('id_operadora') }}"
      - name: operadora
        description: "{{ doc('operadora') }}"
      - name: id_servico_jae
        description: "{{ doc('id_servico_jae') }}"
      - name: servico_jae
        description: "Nome curto da linha operada pelo veículo com variação de serviço (ex: 010, 011SN, ...) ou código da estação de BRT na Jaé"
      - name: descricao_servico_jae
        description: "{{ doc('descricao_servico_jae') }}"
      # - name: servico
      #   description: "Nome curto da linha operada pelo veículo com variação de serviço (ex: 010, 011SN, ...) ou código da estação"
      - name: id_ordem_pagamento
        description: "Identificador da ordem pagamento no banco de dados da Jaé"
      - name: id_ordem_rateio
        description: "Identificador único da ordem de rateio da transação"
      - name: quantidade_transacao_debito
        description: "Quantidade de transações feitas na modalidade débito"
      - name: valor_debito
        description: "Valor total das transações feitas na modalidade débito (R$)"
      - name: quantidade_transacao_especie
        description: "{{ doc('quantidade_transacao_especie') }}"
      - name: valor_especie
        description: "Valor total das transações feitas em espécie (R$)"
      - name: quantidade_transacao_gratuidade
        description: "Quantidade de transações feitas com gratuidade"
      - name: valor_gratuidade
        description: "Valor total das transações feitas com gratuidade (R$)"
      - name: quantidade_transacao_integracao
        description: "Quantidade de transações feitas com integração"
      - name: valor_integracao
        description: "Valor total das transações feitas com integração (R$)"
      - name: quantidade_transacao_rateio_credito
        description: "Quantidade total de transações consideradas no crédito da repartição tarifária"
      - name: valor_rateio_credito
        description: "Valor total creditado em decorrência da repartição tarifária (R$)"
      - name: quantidade_transacao_rateio_debito
        description: "Quantidade total de transações consideradas no débito da repartição tarifária"
      - name: valor_rateio_debito
        description: "Valor total debitado em decorrência da repartição tarifária (R$)"
      - name: quantidade_total_transacao
        description: "{{ doc('quantidade_total_transacao') }}"
      - name: valor_total_transacao_bruto
        description: "Valor total das transações realizadas (R$)"
      - name: valor_desconto_taxa
        description: "Valor da taxa descontado do valor total (R$)"
      - name: valor_total_transacao_liquido
        description: "Valor total das transações menos o valor_desconto_taxa (R$)"
      - name: quantidade_total_transacao_captura
        description: "Quantidade total de transações calculada pela captura de transações"
      - name: valor_total_transacao_captura
        description: "Valor total das transações realizadas calculada pela captura de transações (R$)"
      - name: versao
        description: "{{ doc('versao') }}"
