FROM python:3.10-slim as dbt-generate

# Setup virtual environment
ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# Copy and install dependencies
WORKDIR /tmp
COPY ./requirements.txt requirements-docs.txt
RUN pip install --no-cache-dir -r requirements-docs.txt && \
    rm requirements.txt

# Copy dbt project and profiles
WORKDIR /dbt
COPY . .

# Generate and serve docs
CMD ["dbt", "docs", "serve", "--profiles-dir", ".", "--port", "3000"]