queries:
  outputs:
    dev:
      dataset: dbt
      job_execution_timeout_seconds: 600
      job_retries: 1
      keyfile: /tmp/credentials.json
      location: us
      method: service-account
      priority: interactive
      project: rj-smtr-dev
      threads: 1
      type: bigquery
    prod:
      dataset: dbt
      job_execution_timeout_seconds: 600
      job_retries: 1
      keyfile: /tmp/credentials.json
      location: us
      method: service-account
      priority: interactive
      project: rj-smtr
      threads: 1
      type: bigquery
  target: dev
