queries:
  outputs:
    dev:
      dataset: dbt
      job_execution_timeout_seconds: 5400
      job_retries: 1
      keyfile: /tmp/credentials.json
      location: us
      method: service-account
      priority: interactive
      project: rj-smtr-dev
      threads: 1
      type: bigquery

      # for dbt Python models to be run on Dataproc Serverless
      gcs_bucket: rj-smtr
      dataproc_region: us-central1
      submission_method: serverless
      dataproc_batch:
        environment_config:
          execution_config:
            service_account: prefect@rj-smtr-dev.iam.gserviceaccount.com

        runtime_config:
          properties:
            spark.executor.instances: "2"
            spark.driver.memory: 4g
            spark.driver.memoryOverhead: 1g
    hmg:
      dataset: dbt
      job_execution_timeout_seconds: 5400
      job_retries: 1
      keyfile: /tmp/credentials.json
      location: us
      method: service-account
      priority: interactive
      project: rj-smtr-dev
      threads: 1
      type: bigquery

      # for dbt Python models to be run on Dataproc Serverless
      gcs_bucket: rj-smtr
      dataproc_region: us-central1
      submission_method: serverless
      dataproc_batch:
        environment_config:
          execution_config:
            service_account: prefect@rj-smtr-dev.iam.gserviceaccount.com

        runtime_config:
          properties:
            spark.executor.instances: "2"
            spark.driver.memory: 4g
            spark.driver.memoryOverhead: 1g
    prod:
      dataset: dbt
      job_execution_timeout_seconds: 5400
      job_retries: 1
      keyfile: /tmp/credentials.json
      location: us
      method: service-account
      priority: interactive
      project: rj-smtr
      threads: 1
      type: bigquery

      # for dbt Python models to be run on Dataproc Serverless
      gcs_bucket: rj-smtr
      dataproc_region: us-central1
      submission_method: serverless
      dataproc_batch:
        environment_config:
          execution_config:
            service_account: prefect@rj-smtr.iam.gserviceaccount.com

        runtime_config:
          properties:
            spark.executor.instances: "2"
            spark.driver.memory: 4g
            spark.driver.memoryOverhead: 1g
  target: prod