version: 2

models:
  - name: aux_viagem_temperatura
    description: "Tabela auxiliar com indicadores de temperatura e validadores por viagem"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - data
            - id_viagem
          name: dbt_utils.unique_combination_of_columns__aux_viagem_temperatura
    columns:
      - name: data
        description: "{{ doc('data_viagem') }} [partição]"
        tests:
          - not_null:
              name: not_null__data__viagem_temperatura
      - name: id_viagem
        description: "{{ doc('id_viagem') }}"
        tests:
          - not_null:
              name: not_null__id_viagem__viagem_temperatura
      - name: id_veiculo
        description: "{{ doc('id_veiculo') }}"
        tests:
          - not_null:
              name: not_null__id_veiculo__viagem_temperatura
      - name: datetime_partida
        description: "{{ doc('datetime_partida') }}"
        tests:
          - not_null:
              name: not_null__datetime_partida__viagem_temperatura
      - name: datetime_chegada
        description: "{{ doc('datetime_chegada') }}"
        tests:
          - not_null:
              name: not_null__datetime_chegada__viagem_temperatura
      - name: modo
        description: "{{ doc('modo') }}"
      - name: ano_fabricacao
        description: "{{ doc('ano_fabricacao') }}"
        tests:
          - not_null:
              name: not_null__ano_fabricacao__viagem_temperatura
      - name: tecnologia_apurada
        description: "{{ doc('tecnologia') }}"
        tests:
          - not_null:
              name: not_null__tecnologia_apurada__viagem_temperatura
      - name: tecnologia_remunerada
        description: "{{ doc('tecnologia_remunerada') }}"
        tests:
          - not_null:
              name: not_null__tecnologia_remunerada__viagem_temperatura
      - name: tipo_viagem
        description: "{{ doc('tipo_viagem_status') }}"
        tests:
          - not_null:
              name: not_null__tipo_viagem__viagem_temperatura
      - name: indicadores
        description: "Indicadores expandidos incluindo temperatura, validadores e ar condicionado"
        tests:
          - not_null:
              name: not_null__indicadores__viagem_temperatura
      - name: servico
        description: "{{ doc('servico') }}"
        tests:
          - not_null:
              name: not_null__servico__viagem_temperatura
      - name: sentido
        description: "{{ doc('sentido') }}"
        tests:
          - not_null:
              name: not_null__sentido__viagem_temperatura
      - name: distancia_planejada
        description: "{{ doc('distancia_planejada') }}"
        tests:
          - not_null:
              name: not_null__distancia_planejada__viagem_temperatura
      - name: datetime_ultima_atualizacao
        description: "{{ doc('datetime_ultima_atualizacao') }}"
      - name: versao
        description: "{{ doc('versao') }}"
      - name: id_execucao_dbt
        description: "{{ doc('id_execucao_dbt') }}"