version: 2

models:
  - name: aux_viagem_temperatura
    description: "Tabela auxiliar com indicadores de temperatura e validadores por viagem"
    columns:
      - name: data
        description: "{{ doc('data_viagem') }} [partição]"
      - name: id_viagem
        description: "{{ doc('id_viagem') }}"
      - name: id_veiculo
        description: "{{ doc('id_veiculo') }}"
      - name: datetime_partida
        description: "{{ doc('datetime_partida') }}"
      - name: datetime_chegada
        description: "{{ doc('datetime_chegada') }}"
      - name: modo
        description: "{{ doc('modo') }}"
      - name: ano_fabricacao
        description: "{{ doc('ano_fabricacao') }}"
      - name: tecnologia_apurada
        description: "{{ doc('tecnologia') }}"
      - name: tecnologia_remunerada
        description: "{{ doc('tecnologia_remunerada') }}"
      - name: tipo_viagem
        description: "{{ doc('tipo_viagem_status') }}"
      - name: indicadores
        description: "Indicadores expandidos incluindo temperatura, validadores e ar condicionado"
      - name: servico
        description: "{{ doc('servico') }}"
      - name: sentido
        description: "{{ doc('sentido') }}"
      - name: distancia_planejada
        description: "{{ doc('distancia_planejada') }}"
      - name: datetime_ultima_atualizacao
        description: "{{ doc('datetime_ultima_atualizacao') }}"
      - name: versao
        description: "{{ doc('versao') }}"
      - name: id_execucao_dbt
        description: "{{ doc('id_execucao_dbt') }}"