version: 2

models:
  - name: balanco_consorcio_ano
    latest_version: 2
    versions:
      - v: 1
      - v: 2
    description: "Balanço da receita aferida e esperada por consórcio e ano para serviços-dia subsidiados. Ver metodologia nas notas técnicas TR/SUBTT Nº 01/2024 e 01/2025."
    columns:
      - name: ano
        description: "{{ doc('ano') }}"
      - name: consorcio
        description: "{{ doc('consorcio') }}"
      - name: km_subsidiada
        description: "{{ doc('km_subsidiada') }}"
      - name: km_apurada
        description: "{{ doc('km_apurada') }}"
      - name: receita_total_esperada
        description: "{{ doc('receita_total_esperada') }}"
      - name: receita_tarifaria_esperada
        description: "{{ doc('receita_tarifaria_esperada') }}"
      - name: subsidio_esperado
        description: "{{ doc('subsidio_esperado') }}"
      - name: subsidio_glosado
        description: "{{ doc('subsidio_glosado') }}"
      - name: receita_total_aferida
        description: "{{ doc('receita_total_aferida') }}"
      - name: receita_tarifaria_aferida
        description: "{{ doc('receita_tarifaria_aferida') }}"
      - name: subsidio_pago
        description: "{{ doc('subsidio_pago') }}"
      - name: saldo
        description: "{{ doc('saldo') }}"
  - name: balanco_consorcio_dia
    latest_version: 2
    versions:
      - v: 1
      - v: 2
    description: "Balanço da receita aferida e esperada por consórcio e dia para serviços-dia subsidiados. Ver metodologia nas notas técnicas TR/SUBTT Nº 01/2024 e 01/2025."
    columns:
      - name: data
        description: "{{ doc('data') }}"
      - name: consorcio
        description: "{{ doc('consorcio') }}"
      - name: km_subsidiada
        description: "{{ doc('km_subsidiada') }}"
      - name: receita_total_esperada
        description: "{{ doc('receita_total_esperada') }}"
      - name: receita_tarifaria_esperada
        description: "{{ doc('receita_tarifaria_esperada') }}"
      - name: subsidio_esperado
        description: "{{ doc('subsidio_esperado') }}"
      - name: subsidio_glosado
        description: "{{ doc('subsidio_glosado') }}"
      - name: receita_total_aferida
        description: "{{ doc('receita_total_aferida') }}"
      - name: receita_tarifaria_aferida
        description: "{{ doc('receita_tarifaria_aferida') }}"
      - name: subsidio_pago
        description: "{{ doc('subsidio_pago') }}"
      - name: saldo
        description: "{{ doc('saldo') }}"
  - name: balanco_servico_ano
    latest_version: 2
    versions:
      - v: 1
      - v: 2
    description: "Balanço da receita aferida e esperada por serviço e ano para serviços-dia subsidiados. Ver metodologia nas notas técnicas TR/SUBTT Nº 01/2024 e 01/2025."
    columns:
      - name: ano
        description: "{{ doc('ano') }}"
      - name: consorcio
        description: "{{ doc('consorcio') }}"
      - name: servico
        description: "{{ doc('servico') }}"
      - name: km_subsidiada
        description: "{{ doc('km_subsidiada') }}"
      - name: receita_total_esperada
        description: "{{ doc('receita_total_esperada') }}"
      - name: receita_tarifaria_esperada
        description: "{{ doc('receita_tarifaria_esperada') }}"
      - name: subsidio_esperado
        description: "{{ doc('subsidio_esperado') }}"
      - name: subsidio_glosado
        description: "{{ doc('subsidio_glosado') }}"
      - name: receita_total_aferida
        description: "{{ doc('receita_total_aferida') }}"
      - name: receita_tarifaria_aferida
        description: "{{ doc('receita_tarifaria_aferida') }}"
      - name: subsidio_pago
        description: "{{ doc('subsidio_pago') }}"
      - name: saldo
        description: "{{ doc('saldo') }}"
  - name: balanco_servico_dia
    latest_version: 2
    versions:
      - v: 1
      - v: 2
    description: "Balanço da receita aferida e esperada por servico e dia para serviços-dia subsidiados. Ver metodologia nas notas técnicas TR/SUBTT Nº 01/2024 e 01/2025"
    columns:
      - name: data
        description: "{{ doc('data') }}"
      - name: consorcio
        description: "{{ doc('consorcio') }}"
      - name: servico
        description: "{{ doc('servico') }}"
      - name: km_subsidiada
        description: "{{ doc('km_subsidiada') }}"
      - name: receita_total_esperada
        description: "{{ doc('receita_total_esperada') }}"
      - name: receita_tarifaria_esperada
        description: "{{ doc('receita_tarifaria_esperada') }}"
      - name: subsidio_esperado
        description: "{{ doc('subsidio_esperado') }}"
      - name: subsidio_glosado
        description: "{{ doc('subsidio_glosado') }}"
      - name: receita_total_aferida
        description: "{{ doc('receita_total_aferida') }}"
      - name: receita_tarifaria_aferida
        description: "{{ doc('receita_tarifaria_aferida') }}"
      - name: subsidio_pago
        description: "{{ doc('subsidio_pago') }}"
      - name: saldo
        description: "{{ doc('saldo') }}"
  - name: balanco_servico_dia_pos_gt
    latest_version: 1
    versions:
      - v: 1
    description: "Balanço da receita aferida e esperada por servico e dia para serviços-dia subsidiados após alterações do Grupo de Trabalho [Processo.Rio MTR-PRO-2024/06270]. Ver metodologia nas notas técnicas TR/SUBTT Nº 01/2024, 02/2024 e 01/2025."
    columns:
      - name: data
        description: "{{ doc('data') }}"
      - name: consorcio
        description: "{{ doc('consorcio') }}"
      - name: servico
        description: "{{ doc('servico') }}"
      - name: km_subsidiada
        description: "{{ doc('km_subsidiada') }}"
      - name: receita_total_esperada
        description: "{{ doc('receita_total_esperada') }}"
      - name: receita_tarifaria_esperada
        description: "{{ doc('receita_tarifaria_esperada') }}"
      - name: subsidio_esperado
        description: "{{ doc('subsidio_esperado') }}"
      - name: subsidio_glosado
        description: "{{ doc('subsidio_glosado') }}"
      - name: receita_total_aferida
        description: "{{ doc('receita_total_aferida') }}"
      - name: receita_tarifaria_aferida
        description: "{{ doc('receita_tarifaria_aferida') }}"
      - name: subsidio_pago
        description: "{{ doc('subsidio_pago') }}"
      - name: saldo
        description: "{{ doc('saldo') }}"
  - name: balanco_servico_quinzena
    latest_version: 2
    versions:
      - v: 1
      - v: 2
    description: "Balanço da receita aferida e esperada por serviço e quinzena para serviços-dia subsidiados. Ver metodologia nas notas técnicas TR/SUBTT Nº 01/2024 e 01/2025."
    columns:
      - name: quinzena
        description: "{{ doc('quinzena') }}"
      - name: data_inicial_quinzena
        description: "{{ doc('data_inicial_quinzena') }}"
      - name: data_final_quinzena
        description: "{{ doc('data_final_quinzena') }}"
      - name: consorcio
        description: "{{ doc('consorcio') }}"
      - name: servico
        description: "{{ doc('servico') }}"
      - name: quantidade_dias_subsidiado
        description: "Quantidade de dias em que o serviço recebeu subsídio na quinzena"
      - name: km_subsidiada
        description: "{{ doc('km_subsidiada') }}"
      - name: receita_total_esperada
        description: "{{ doc('receita_total_esperada') }}"
      - name: receita_tarifaria_esperada
        description: "{{ doc('receita_tarifaria_esperada') }}"
      - name: subsidio_esperado
        description: "{{ doc('subsidio_esperado') }}"
      - name: subsidio_glosado
        description: "{{ doc('subsidio_glosado') }}"
      - name: receita_total_aferida
        description: "{{ doc('receita_total_aferida') }}"
      - name: receita_tarifaria_aferida
        description: "{{ doc('receita_tarifaria_aferida') }}"
      - name: subsidio_pago
        description: "{{ doc('subsidio_pago') }}"
      - name: saldo
        description: "{{ doc('saldo') }}"
  - name: receita_tarifaria_servico_nao_identificado_quinzena
    description: "Receita tarifária proveniente do RDO para serviços de ônibus dos consórcios que não foram identificados nos planos operacionais dos respectivos dias."
    columns:
      - name: quinzena
        description: "{{ doc('quinzena') }}"
      - name: data_inicial_quinzena
        description: "{{ doc('data_inicial_quinzena') }}"
      - name: data_final_quinzena
        description: "{{ doc('data_final_quinzena') }}"
      - name: consorcio_rdo
        description: "{{ doc('consorcio') }} informado no RDO"
      - name: servico_tratado_rdo
        description: "Serviço tratado (linha) extraído do campo 'linha' do RDO, após tratamento"
      - name: linha_rdo
        description: "{{ doc('servico') }} conforme declarada no RDO"
      - name: tipo_servico_rdo
        description: "{{ doc('tipo_servico') }}"
      - name: ordem_servico_rdo
        description: "{{ doc('ordem_servico') }}"
      - name: quantidade_dias_rdo
        description: "Quantidade de dias em que o serviço foi encontrado no RDO na respectiva quinzena"
      - name: receita_tarifaria_aferida_rdo
        description: "{{ doc('receita_tarifaria_aferida') }}"
  - name: recurso_encontro_contas
    latest_version: 2
    versions:
      - v: 2
  - name: aux_rdo_servico_dia
    latest_version: 2
    versions:
      - v: 2
  - name: aux_subsidio_servico_dia
    latest_version: 2
    versions:
      - v: 2
  - name: staging_encontro_contas_servico_dia
    latest_version: 2
    versions:
      - v: 2
