models:
  - name: recarga_jae
    description: Tabela com os dados de recarga dos cartões da Jaé
    columns:
      - name: data
        description: Data do lançamento da recarga no sistema da Jaé [partição]
        data_type: date
        quote: true
      - name: id_lancamento
        description: Identificador único do lançamento no sistema da Jaé
        data_type: string
        quote: true
      - name: datetime_recarga
        description: Data e hora do lançamento da recarga no sistema da Jaé
        data_type: datetime
        quote: true
      - name: id_cliente
        description: "{{ doc('id_cliente') }}"
        data_type: string
        quote: true
        policy_tags:
          - 'projects/rj-smtr/locations/us/taxonomies/6071707853840412174/policyTags/1168584191451386864'
      - name: id_conta
        description: Identificador único da conta que recebeu a transferência
        data_type: string
        quote: true
        policy_tags:
          - 'projects/rj-smtr/locations/us/taxonomies/6071707853840412174/policyTags/1168584191451386864'
      - name: tipo_conta
        description: Tipo da conta que recebeu a transferência
        data_type: string
        quote: true
      - name: tipo_movimento
        description: Tipo da movimentação financeira
        data_type: string
        quote: true
      - name: valor_recarga
        description: Valor da recarga
        data_type: numeric
        quote: true
      - name: tipo_moeda
        description: Moeda utilizada na recarga (Real ou Crédito eletrônico)
        data_type: string
        quote: true
      - name: versao
        description: "{{ doc('versao') }}"
        data_type: string
        quote: true
      - name: datetime_ultima_atualizacao
        description: "{{ doc('datetime_ultima_atualizacao') }}"
        data_type: datetime
        quote: true
      - name: id_execucao_dbt
        description: "{{ doc('id_execucao_dbt') }}"
        data_type: string
        quote: true
  - name: data_ordem_transacao
    description: Tabela com relacionamento entre data_transacao e data_ordem
    columns:
      - name: data_ordem
        description: "{{ doc('data_ordem') }} [partição]"
        data_type: date
        quote: true
      - name: id_ordem_pagamento_consorcio_operador_dia
        description: "{{ doc('id_ordem_pagamento_consorcio_operador_dia') }}"
        data_type: string
        quote: true
      - name: data_transacao
        description: "{{ doc('data_transacao') }}"
        data_type: date
        quote: true
      - name: versao
        description: "{{ doc('versao') }}"
        data_type: string
        quote: true
      - name: datetime_ultima_atualizacao
        description: "{{ doc('datetime_ultima_atualizacao') }}"
        data_type: datetime
        quote: true
      - name: id_execucao_dbt
        description: "{{ doc('id_execucao_dbt') }}"
        data_type: string
        quote: true
  - name: transacao_gratuidade_estudante_municipal
    description: View com transações de gratuidade dos estudantes da rede municipal
    tests:
      - sincronizacao_tabelas:
          name: sincronizacao_tabelas__transacao_gratuidade_estudante_municipal
          where: ""
          tabela_base: "{{ ref('transacao') }}"
          filtro_tabela_base: |
            tipo_transacao_jae in ('Gratuidade', 'Integração gratuidade')
            and tipo_usuario = "Estudante"
            and subtipo_usuario = 'Ensino Básico Municipal'
          join_key: "id_transacao"
          excluir_colunas:
            - versao
            - datetime_ultima_atualizacao
            - id_execucao_dbt
            - nome_cliente
            - nome_escola
          filtro_particao_modificada: True
    columns:
      - name: data
        description: "{{ doc('data_transacao') }} [partição]"
        data_type: date
      - name: hora
        description: "{{ doc('hora_transacao') }}"
        data_type: int64
      - name: datetime_transacao
        description: "{{ doc('datetime_transacao') }}"
        data_type: datetime
      - name: id_transacao
        description: "{{ doc('id_transacao') }}"
        data_type: string
      - name: modo
        description: "{{ doc('modo') }}"
        data_type: string
      - name: tipo_documento_cliente
        description: "{{ doc('tipo_documento_cliente') }}"
      - name: documento_cliente
        description: "{{ doc('documento_cliente') }}"
        policy_tags:
          - 'projects/rj-smtr/locations/us/taxonomies/6071707853840412174/policyTags/1101226827904472521'
      - name: numero_matricula
        description: Número da matrícula do estudante
        policy_tags:
          - 'projects/rj-smtr/locations/us/taxonomies/6071707853840412174/policyTags/1101226827904472521'
      - name: nome_cliente
        description: "{{ doc('nome_cliente') }}"
        policy_tags:
          - 'projects/rj-smtr/locations/us/taxonomies/6071707853840412174/policyTags/1101226827904472521'
      - name: tipo_transacao_jae
        description: "{{ doc('tipo_transacao_jae') }}"
        data_type: string
      - name: tipo_transacao
        description: "{{ doc('tipo_transacao') }}"
        data_type: string
      - name: tipo_usuario
        description: "{{ doc('tipo_usuario') }}"
        data_type: string
        quote: true
      - name: subtipo_usuario
        description: "{{ doc('subtipo_usuario') }}"
      - name: meio_pagamento
        description: "{{ doc('meio_pagamento') }}"
      - name: id_cre_escola
        description: "{{ doc('id_cre_escola') }} do cliente"
        policy_tags:
          - 'projects/rj-smtr/locations/us/taxonomies/6071707853840412174/policyTags/1101226827904472521'
      - name: nome_escola
        description: Nome da escola
        policy_tags:
          - 'projects/rj-smtr/locations/us/taxonomies/6071707853840412174/policyTags/1101226827904472521'
      - name: versao
        description: "{{ doc('versao') }}"
      - name: datetime_ultima_atualizacao
        description: "{{ doc('datetime_ultima_atualizacao') }}"
      - name: id_execucao_dbt
        description: "{{ doc('id_execucao_dbt') }}"

  - name: extrato_cliente_cartao
    description: Tabela de extrato do cliente
    columns:
      - name: data
        description: "{{ doc('data') }} [partição]"
      - name: datetime_lancamento
        description: Datetime de lançamento do registro de extrato
      - name: id_conta
        description: Identificador único da conta que recebeu a transferência
        policy_tags:
          - 'projects/rj-smtr/locations/us/taxonomies/6071707853840412174/policyTags/1168584191451386864'
      - name: hash_cartao
        description: "{{ doc('hash_cartao') }}"
        policy_tags:
          - 'projects/rj-smtr/locations/us/taxonomies/6071707853840412174/policyTags/1168584191451386864'
      - name: id_lancamento
        description: Identificador único do lançamento da transferência
      - name: id_unico_lancamento
        description: Identificador único do lançamento da transferência com tratamento em caso de valor nulo
      - name: id_cliente
        description: "{{ doc('id_cliente') }}"
        policy_tags:
          - 'projects/rj-smtr/locations/us/taxonomies/6071707853840412174/policyTags/1168584191451386864'
      - name: nome_cliente
        description: "{{ doc('nome_cliente') }}"
      - name: documento_cliente
        description: "{{ doc('documento_cliente') }}"
      - name: tipo_documento_cliente
        description: "{{ doc('tipo_documento_cliente') }}"
      - name: tipo_movimento
        description: Tipo de movimentação do lançamento
      - name: valor_lancamento
        description: Valor da lançamento efetuado
      - name: datetime_captura
        description: "{{ doc('datetime_captura') }}"
      - name: versao
        description: "{{ doc('versao') }}"
      - name: datetime_ultima_atualizacao
        description: "{{ doc('datetime_ultima_atualizacao') }}"
      - name: id_execucao_dbt
        description: "{{ doc('id_execucao_dbt') }}"

