version: 2

models:
  - name: gps_validador
    description: "Tabela de posições de GPS de todos os validadores da Jaé, incluindo estado do equipamento [Aberto/Fechado], serviço, sentido e veículo associado e temperatura do veículo"
    columns:
      - name: modo
        description: "Tipo de transporte (Ônibus, Van, BRT)"
      - name: data
        description: "Data do recebimento da transmissão do GPS (partição)"
      - name: hora
        description: "Hora do recebimento da transmissão do GPS"
      - name: datetime_gps
        description: "Data e hora do recebimento da transmissão do GPS [GMT-3]"
      - name: datetime_captura
        description: "Data e hora da captura do dado de GPS [GMT-3]"
      - name: id_operadora
        description: "Identificador da operadora na tabela cadastro.operadoras"
      - name: operadora
        description: "{{ doc('operadora') }}"
      # - name: servico
      #   description: "Nome curto da linha operada pelo veículo com variação de serviço (ex: 010, 011SN, ...) ou código da estação"
      - name: id_servico_jae
        description: "Identificador da linha no banco de dados da jaé (É possível cruzar os dados com a tabela rj-smtr.cadastro.servicos usando a coluna id_servico_jae)"
      - name: servico_jae
        description: "Nome curto da linha operada pelo veículo com variação de serviço (ex: 010, 011SN, ...) ou código da estação de BRT na Jaé"
      - name: descricao_servico_jae
        description: "{{ doc('descricao_servico_jae') }}"
      - name: id_validador
        description: "{{ doc('id_validador') }}"
      - name: id_transmissao_gps
        description: "Identificador único da tabela de GPS dos validadores"
      - name: latitude
        description: "Latitude do validador no momento da transmissão"
      - name: longitude
        description: "Longitude do validador no momento da transmissão"
      - name: id_veiculo
        description: "[EM DESENVOLVIMENTO] Código identificador do veículo (número de ordem)"
      - name: sentido
        description: "{{ doc('sentido') }}"
      - name: estado_equipamento
        description: "Validador aberto ou fechado no momento da transmissão"
      - name: temperatura
        description: "Temperatura do local, medida pelo sensor do validador (ºC)"
      - name: versao_app
        description: "Versão do Software do validador"
      - name: versao
        description: "{{ doc('versao') }}"
  - name: gps_validador_van
    description: "Tabela de posições de GPS de todos os validadores da Jaé instalados em vans, incluindo estado do equipamento [Aberto/Fechado], serviço, sentido e veículo associado e temperatura do veículo"
    columns:
      - name: modo
        description: "Tipo de transporte (Ônibus, Van, BRT)"
      - name: data
        description: "Data do recebimento da transmissão do GPS (partição)"
      - name: hora
        description: "Hora do recebimento da transmissão do GPS"
      - name: datetime_gps
        description: "Data e hora do recebimento da transmissão do GPS [GMT-3]"
      - name: datetime_captura
        description: "Data e hora da captura do dado de GPS [GMT-3]"
      - name: id_operadora
        description: "Identificador da operadora na tabela cadastro.operadoras"
      - name: operadora
        description: "{{ doc('operadora') }}"
      # - name: servico
      #   description: "Nome curto da linha operada pelo veículo com variação de serviço (ex: 010, 011SN, ...)"
      - name: id_servico_jae
        description: "Identificador da linha no banco de dados da jaé (É possível cruzar os dados com a tabela rj-smtr.cadastro.servicos usando a coluna id_servico_jae)"
      - name: servico_jae
        description: "Nome curto da linha operada pelo veículo com variação de serviço (ex: 010, 011SN, ...) ou código da estação de BRT na Jaé"
      - name: descricao_servico_jae
        description: "{{ doc('descricao_servico_jae') }}"
      - name: id_validador
        description: "{{ doc('id_validador') }}"
      - name: id_transmissao_gps
        description: "Identificador único da tabela de GPS dos validadores"
      - name: latitude
        description: "Latitude do validador no momento da transmissão [protegido]"
        policy_tags:
          - 'projects/rj-smtr/locations/us/taxonomies/388050497607535163/policyTags/5185403103447535390'
      - name: longitude
        description: "Longitude do validador no momento da transmissão [protegido]"
        policy_tags:
          - 'projects/rj-smtr/locations/us/taxonomies/388050497607535163/policyTags/5185403103447535390'
      - name: id_veiculo
        description: "[EM DESENVOLVIMENTO] Código identificador do veículo (número de ordem)"
      - name: sentido
        description: "{{ doc('sentido') }}"
      - name: estado_equipamento
        description: "Validador aberto ou fechado no momento da transmissão"
      - name: temperatura
        description: "Temperatura do local, medida pelo sensor do validador (ºC)"
      - name: versao_app
        description: "Versão do Software do validador"
      - name: versao
        description: "{{ doc('versao') }}"
  - name: ordem_pagamento_consorcio_dia
    description: "Tabela com os valores totais de pagamento da Jaé agregados por consorcio e dia"
    columns:
      - name: data_ordem
        description: "Data da ordem de pagamento (partição)"
      - name: id_consorcio
        description: "{{ doc('id_consorcio') }}"
      - name: consorcio
        description: "Nome do consórcio"
      - name: id_ordem_pagamento
        description: "Identificador da ordem pagamento no banco de dados da Jaé"
      - name: quantidade_transacao_debito
        description: "Quantidade de transações feitas na modalidade débito"
      - name: valor_debito
        description: "Valor total das transações feitas na modalidade débito (R$)"
      - name: quantidade_transacao_especie
        description: "{{ doc('quantidade_transacao_especie') }}"
      - name: valor_especie
        description: "Valor total das transações feitas em espécie (R$)"
      - name: quantidade_transacao_gratuidade
        description: "Quantidade de transações feitas com gratuidade"
      - name: valor_gratuidade
        description: "Valor total das transações feitas com gratuidade (R$)"
      - name: quantidade_transacao_integracao
        description: "Quantidade de transações feitas com integração"
      - name: valor_integracao
        description: "Valor total das transações feitas com integração (R$)"
      - name: quantidade_transacao_rateio_credito
        description: "Quantidade total de transações consideradas no crédito da repartição tarifária"
      - name: valor_rateio_credito
        description: "Valor total creditado em decorrência da repartição tarifária (R$)"
      - name: quantidade_transacao_rateio_debito
        description: "Quantidade total de transações consideradas no débito da repartição tarifária"
      - name: valor_rateio_debito
        description: "Valor total debitado em decorrência da repartição tarifária (R$)"
      - name: quantidade_total_transacao
        description: "{{ doc('quantidade_total_transacao') }}"
      - name: valor_total_transacao_bruto
        description: "Valor total das transações realizadas (R$)"
      - name: valor_total_transacao_liquido
        description: "Valor total das transações menos o valor_desconto_taxa (R$)"
      - name: valor_desconto_taxa
        description: "Valor da taxa descontado do valor total (R$)"
      - name: versao
        description: "{{ doc('versao') }}"
  - name: ordem_pagamento_consorcio_operador_dia
    description: "Tabela com os valores totais de pagamento da Jaé agregados por consorcio, operador e dia"
    columns:
      - name: data_ordem
        description: "Data da ordem de pagamento (partição)"
        tests:
          - dbt_expectations.expect_column_max_to_be_between:
              min_value: "current_date('America/Sao_Paulo')"
              strictly: false
              where: "1=1"
              name: dbt_expectations.expect_column_max_to_be_between__data_ordem__ordem_pagamento_consorcio_operador_dia

      - name: id_ordem_pagamento_consorcio_operador_dia
        description: "Identificador único do registro no banco de dados da Jaé"
        tests:
          - not_null:
              where: "data_ordem in ({partitions})"
              name: not_null__id_ordem_pagamento_consorcio_operador_dia__ordem_pagamento_consorcio_operador_dia
      - name: id_consorcio
        description: "{{ doc('id_consorcio') }}"
        tests:
          - not_null:
              where: "data_ordem in ({partitions})"
              name: not_null__id_consorcio__ordem_pagamento_consorcio_operador_dia
      - name: consorcio
        description: "Nome do consórcio"
        tests:
          - not_null:
              where: "data_ordem in ({partitions})"
              name: not_null__consorcio__ordem_pagamento_consorcio_operador_dia
      - name: id_operadora
        description: "Identificador da operadora na tabela cadastro.operadoras"
        tests:
          - not_null:
              where: "data_ordem in ({partitions})"
              name: not_null__id_operadora__ordem_pagamento_consorcio_operador_dia
      - name: operadora
        description: "{{ doc('operadora') }}"
      - name: id_ordem_pagamento
        description: "Identificador da ordem pagamento no banco de dados da Jaé"
        tests:
          - not_null:
              where: "data_ordem in ({partitions})"
              name: not_null__id_ordem_pagamento__ordem_pagamento_consorcio_operador_dia
      - name: quantidade_transacao_debito
        description: "Quantidade de transações feitas na modalidade débito"
      - name: valor_debito
        description: "Valor total das transações feitas na modalidade débito (R$)"
      - name: quantidade_transacao_especie
        description: "{{ doc('quantidade_transacao_especie') }}"
      - name: valor_especie
        description: "Valor total das transações feitas em espécie (R$)"
      - name: quantidade_transacao_gratuidade
        description: "Quantidade de transações feitas com gratuidade"
      - name: valor_gratuidade
        description: "Valor total das transações feitas com gratuidade (R$)"
      - name: quantidade_transacao_integracao
        description: "Quantidade de transações feitas com integração"
      - name: valor_integracao
        description: "Valor total das transações feitas com integração (R$)"
      - name: quantidade_transacao_rateio_credito
        description: "Quantidade total de transações consideradas no crédito da repartição tarifária"
      - name: valor_rateio_credito
        description: "Valor total creditado em decorrência da repartição tarifária (R$)"
      - name: quantidade_transacao_rateio_debito
        description: "Quantidade total de transações consideradas no débito da repartição tarifária"
      - name: valor_rateio_debito
        description: "Valor total debitado em decorrência da repartição tarifária (R$)"
      - name: quantidade_total_transacao
        description: "{{ doc('quantidade_total_transacao') }}"
      - name: valor_total_transacao_bruto
        description: "Valor total das transações realizadas (R$)"
      - name: valor_desconto_taxa
        description: "Valor da taxa descontado do valor total (R$)"
      - name: valor_total_transacao_liquido_ordem
        description: "Valor total das transações menos o valor_desconto_taxa (R$)"
      - name: valor_total_transacao_liquido
        description: "Valor corrigido total das transações menos o valor_desconto_taxa (R$)"
      - name: data_pagamento
        description: "Data em que foi realizado o pagamento ao operador ou consórcio"
      - name: valor_pago
        description: "Valor pago ao operador ou consórcio (R$)"
      - name: datetime_captura
        description: "Data e hora da captura da ordem [GMT-3]"
      - name: versao
        description: "{{ doc('versao') }}"
      - name: datetime_ultima_atualizacao
        data_type: datetime
        quote: true
        description: "{{ doc('datetime_ultima_atualizacao') }}"
  - name: ordem_pagamento_dia
    description: "Tabela com os valores totais de pagamento da Jaé agregados por dia"
    columns:
      - name: data_ordem
        description: "Data da ordem de pagamento (partição)"
      - name: data_pagamento
        description: "Data de pagamento"
      - name: id_ordem_pagamento
        description: "Identificador da ordem pagamento no banco de dados da Jaé"
      - name: quantidade_transacao_debito
        description: "Quantidade de transações feitas na modalidade débito"
      - name: valor_debito
        description: "Valor total das transações feitas na modalidade débito (R$)"
      - name: quantidade_transacao_especie
        description: "{{ doc('quantidade_transacao_especie') }}"
      - name: valor_especie
        description: "Valor total das transações feitas em espécie (R$)"
      - name: quantidade_transacao_gratuidade
        description: "Quantidade de transações feitas com gratuidade"
      - name: valor_gratuidade
        description: "Valor total das transações feitas com gratuidade (R$)"
      - name: quantidade_transacao_integracao
        description: "Quantidade de transações feitas com integração"
      - name: valor_integracao
        description: "Valor total das transações feitas com integração (R$)"
      - name: quantidade_transacao_rateio_credito
        description: "Quantidade total de transações consideradas no crédito da repartição tarifária"
      - name: valor_rateio_credito
        description: "Valor total creditado em decorrência da repartição tarifária (R$)"
      - name: quantidade_total_transacao
        description: "{{ doc('quantidade_total_transacao') }}"
      - name: quantidade_transacao_rateio_debito
        description: "Quantidade total de transações consideradas no débito da repartição tarifária"
      - name: valor_rateio_debito
        description: "Valor total debitado em decorrência da repartição tarifária (R$)"
      - name: valor_total_transacao_bruto
        description: "Valor total das transações realizadas (R$)"
      - name: valor_desconto_taxa
        description: "Valor da taxa descontado do valor total (R$)"
      - name: valor_total_transacao_liquido
        description: "Valor total das transações menos o valor_desconto_taxa (R$)"
      - name: versao
        description: "{{ doc('versao') }}"
  - name: ordem_pagamento_servico_operador_dia
    descriptions: "Tabela com os valores totais de pagamento da Jaé agregados por serviço, operador e dia"
    columns:
      - name: data_ordem
        description: "Data da ordem de pagamento (partição)"
      - name: id_consorcio
        description: "{{ doc('id_consorcio') }}"
      - name: consorcio
        description: "Nome do consórcio"
      - name: id_operadora
        description: "Identificador da operadora na tabela cadastro.operadoras"
      - name: operadora
        description: "{{ doc('operadora') }}"
      - name: id_servico_jae
        description: "Identificador da linha no banco de dados da jaé (É possível cruzar os dados com a tabela rj-smtr.cadastro.servicos usando a coluna id_servico_jae)"
      - name: servico_jae
        description: "Nome curto da linha operada pelo veículo com variação de serviço (ex: 010, 011SN, ...) ou código da estação de BRT na Jaé"
      - name: descricao_servico_jae
        description: "{{ doc('descricao_servico_jae') }}"
      # - name: servico
      #   description: "Nome curto da linha operada pelo veículo com variação de serviço (ex: 010, 011SN, ...) ou código da estação"
      - name: id_ordem_pagamento
        description: "Identificador da ordem pagamento no banco de dados da Jaé"
      - name: id_ordem_rateio
        description: "Identificador único da ordem de rateio da transação"
      - name: quantidade_transacao_debito
        description: "Quantidade de transações feitas na modalidade débito"
      - name: valor_debito
        description: "Valor total das transações feitas na modalidade débito (R$)"
      - name: quantidade_transacao_especie
        description: "{{ doc('quantidade_transacao_especie') }}"
      - name: valor_especie
        description: "Valor total das transações feitas em espécie (R$)"
      - name: quantidade_transacao_gratuidade
        description: "Quantidade de transações feitas com gratuidade"
      - name: valor_gratuidade
        description: "Valor total das transações feitas com gratuidade (R$)"
      - name: quantidade_transacao_integracao
        description: "Quantidade de transações feitas com integração"
      - name: valor_integracao
        description: "Valor total das transações feitas com integração (R$)"
      - name: quantidade_transacao_rateio_credito
        description: "Quantidade total de transações consideradas no crédito da repartição tarifária"
      - name: valor_rateio_credito
        description: "Valor total creditado em decorrência da repartição tarifária (R$)"
      - name: quantidade_transacao_rateio_debito
        description: "Quantidade total de transações consideradas no débito da repartição tarifária"
      - name: valor_rateio_debito
        description: "Valor total debitado em decorrência da repartição tarifária (R$)"
      - name: quantidade_total_transacao
        description: "{{ doc('quantidade_total_transacao') }}"
      - name: valor_total_transacao_bruto
        description: "Valor total das transações realizadas (R$)"
      - name: valor_desconto_taxa
        description: "Valor da taxa descontado do valor total (R$)"
      - name: valor_total_transacao_liquido
        description: "Valor total das transações menos o valor_desconto_taxa (R$)"
      - name: quantidade_total_transacao_captura
        description: "Quantidade total de transações calculada pela captura de transações"
      - name: valor_total_transacao_captura
        description: "Valor total das transações realizadas calculada pela captura de transações (R$)"
      - name: versao
        description: "{{ doc('versao') }}"
