
version: 2

models:
  - name: subsidio_shapes_geom
    description: "Shapes em formatos geográficos dos serviços [Descontinuada a partir de 2024-04-01]"
    columns:
      - name: shape_id
        description: "{{ doc('shape_id') }}"
      - name: shape
        description: "{{ doc('shape') }}"
      - name: shape_distance
        description: "{{ doc('shape_distance') }}"
      - name: start_pt
        description: "{{ doc('start_pt') }}"
      - name: end_pt
        description: "{{ doc('end_pt') }}"
      - name: data_versao
        description: "{{ doc('data_versao') }}"
      - name: versao_modelo
        description: "{{ doc('versao') }}"
  - name: subsidio_trips_desaninhada
    description: "Viagens para cada serviço [Descontinuada a partir de 2024-04-01]"
    columns:
      - name: trip_id
        description: "{{ doc('trip_id') }}"
      - name: route_id
        description: "{{ doc('route_id') }}"
      - name: trip_headsign
        description: "{{ doc('trip_headsign') }}"
      - name: trip_short_name
        description: "{{ doc('trip_short_name') }}"
      - name: shape_id
        description: "{{ doc('shape_id') }}"
      - name: wheelchair_accessible
        description: "Indica acessibilidade para cadeiras de rodas"
      - name: variacao_itinerario
        description: "Apenas Dia Útil (DU)"
      - name: data_versao
        description: "{{ doc('data_versao') }}"
      - name: versao_modelo
        description: "{{ doc('versao') }}"
  - name: subsidio_quadro_horario
    description: "Dados de planejamento operacional dos serviços [Descontinuada a partir de 2024-04-01]"
    columns:
      - name: data_versao
        description: "{{ doc('data_versao') }}"
      - name: servico
        description: "{{ doc('servico_variacao') }}"
      - name: vista
        description: "{{ doc('vista') }}"
      - name: consorcio
        description: "Nome do consórcio responsável pelo serviço"
      - name: horario_inicio
        description: "{{ doc('horario_inicio') }}"
      - name: horario_fim
        description: "Horário da final de funcionamento do serviço"
      - name: distancia_planejada
        description: "Distância planejada de uma viagem do serviço (km)"
      - name: sentido
        description: "{{ doc('sentido') }}"
      - name: trip_id
        description: "{{ doc('trip_id') }}"
      - name: tipo_dia
        description: "{{ doc('tipo_dia') }}"
      - name: distancia_total_planejada
        description: "Distância total planejada do serviço em km (junta ida+volta multiplicado pela quantidade de viagens)"
      - name: versao_modelo
        description: "{{ doc('versao') }}"
