
version: 2

models:
  - name: subsidio_shapes_geom
    description: "Shapes em formatos geográficos dos serviços (Descontinuada a partir de 2024-04-01 [SUBSIDIO_V6])"
    columns:
      - name: shape_id
        description: "{{ doc('shape_id') }}"
      - name: shape
        description: "{{ doc('shape') }}"
      - name: shape_distance
        description: "Extensão do shape"
      - name: start_pt
        description: "Ponto inicial do shape em formato geográfico (Point)"
      - name: end_pt
        description: "Ponto final do shape em formato geográfico (Point)"
      - name: data_versao
        description: "{{ doc('data_versao') }}"
      - name: versao_modelo
        description: "{{ doc('versao') }}"
  - name: subsidio_trips_desaninhada
    description: "Viagens para cada serviço (Descontinuada a partir de 2024-04-01 [SUBSIDIO_V6])"
    columns:
      - name: trip_id
        description: "Identifica uma viagem"
      - name: route_id
        description: "Identifica uma rota"
      - name: trip_headsign
        description: "Texto que aparece na sinalização identificando o destino da viagem aos passageiros"
      - name: trip_short_name
        description: "Texto voltado ao público usado para identificar a viagem aos passageiros, por exemplo, para identificar os números dos trens para viagens de trens suburbanos"
      - name: shape_id
        description: "{{ doc('shape_id') }}"
      - name: wheelchair_accessible
        description: "Indica acessibilidade para cadeiras de rodas"
      - name: variacao_itinerario
        description: "Apenas Dia Útil (DU)"
      - name: data_versao
        description: "{{ doc('data_versao') }}"
      - name: versao_modelo
        description: "{{ doc('versao') }}"
  - name: subsidio_quadro_horario
    description: "Dados de planejamento operacional dos serviços (Descontinuada a partir de 2024-04-01 [SUBSIDIO_V6])"
    columns:
      - name: data_versao
        description: "{{ doc('data_versao') }}"
      - name: servico
        description: "Nome curto do serviço operada pelo veículo com variação de serviço (ex: 006, 010, ...)"
      - name: vista
        description: "Itinerário do serviço (ex: Bananal ↔ Saens Peña)"
      - name: consorcio
        description: "Nome do consórcio responsável pelo serviço"
      - name: horario_inicio
        description: "Horário inicial de funcionamento do serviço"
      - name: horario_fim
        description: "Horário da final de funcionamento do serviço"
      - name: distancia_planejada
        description: "Distância planejada de uma viagem do serviço (km)"
      - name: sentido
        description: "Sentido planejado - categorias: I (ida), V (volta), C (circular)"
      - name: trip_id
        description: "{{ doc('trip_id_planejado') }}"
      - name: tipo_dia
        description: "Dia da semana - categorias: Dia Útil, Sabado, Domingo e Ponto Facultativo"
      - name: distancia_total_planejada
        description: "Distância total planejada do serviço em km (junta ida+volta multiplicado pela quantidade de viagens)"
      - name: versao_modelo
        description: "{{ doc('versao') }}"
