version: 2

models:
  - name: staging_gps
    description: "Tabela com todos os registros de GPS da API {{ var('fonte_gps') }}"
    tests:
      - check_gps_capture:
          table_id: registros
          interval: 1
          name: check_gps_capture__staging_gps
    columns:
      - name: data
        # description:
        # "{{ doc('data_captura') }}"
      - name: hora
        description: "{{ doc('hora_captura') }}"
      - name: datetime_gps
        description: "{{ doc('timestamp_gps') }}"
      - name: id_veiculo
        description: "{{ doc('id_veiculo') }}"
      - name: servico
        description: "{{ doc('servico') }}"
      - name: sentido
        description: "{{ doc('sentido') }}"
      - name: latitude
        description: "{{ doc('latitude_gps') }}"
      - name: longitude
        description: "{{ doc('longitude_gps') }}"
      - name: velocidade
        description: "{{ doc('velocidade_instantanea') }}"
      - name: direcao
        description: "{{ doc('direcao_gps') }}"
      - name: route_id
        description: "{{ doc('route_id') }}"
      - name: trip_id
        description: "{{ doc('trip_id') }}"
      - name: shape_id
        description: "{{ doc('shape_id') }}"
      - name: datetime_envio
        description: "{{ doc('datetime_envio_gps') }}"
      - name: datetime_servidor
        description: "{{ doc('datetime_servidor_gps') }}"
      - name: datetime_captura
        description: "{{ doc('datetime_captura') }}"
  - name: staging_realocacao
    description: "Tabela com todas as realocações de linha informadas pela API {{ var('fonte_gps') }}"
    tests:
      - check_gps_capture:
          table_id: realocacao
          interval: 10
          name: check_gps_capture__staging_realocacao
    columns:
      - name: data
        description: "{{ doc('data_captura') }}"
      - name: hora
        description: "{{ doc('hora_captura') }}"
      - name: datetime_operacao
        description: "{{ doc('datetime_operacao') }}"
      - name: id_veiculo
        description: "{{ doc('id_veiculo') }}"
      - name: servico
        description: "{{ doc('servico_realocacao') }}"
      - name: datetime_entrada
        description: "{{ doc('datetime_entrada') }}"
      - name: datetime_saida
        description: "{{ doc('datetime_saida') }}"
      - name: datetime_processamento
        description: "{{ doc('datetime_processamento') }}"
      - name: datetime_captura
        description: "{{ doc('datetime_captura') }}"
  - name: staging_garagens
    description: "Tabela com informações das garagens dos operadores"
    columns:
      - name: data
        description: "{{ doc('data_captura') }}"
      - name: operador
        description: "Nome da empresa operadora de transporte público"
      - name: endereco
        description: "Endereço completo da garagem do operador"
      - name: bairro
        description: "Nome do bairro onde está localizada a garagem"
      - name: oficial
        description: "Indicador se a garagem é oficial"
      - name: ativa
        description: "Status operacional da garagem"
      - name: uso
        description: "Tipo de uso da garagem"
      - name: obs
        description: "Observações adicionais sobre a garagem"
      - name: area_m2
        description: "Área total da garagem (m²)"
      - name: geometry_wkt
        description: "Geometria da garagem em formato WKT"
  - name: aux_veiculo_falha_ar_condicionado
    description: "Tabela auxiliar para controle de falhas consecutivas de ar condicionado por veículo"
    columns:
      - name: data
        description: "{{ doc('data') }} [partição]"
        tests:
          - not_null:
              name: not_null__data__aux_veiculo_falha_ar_condicionado
      - name: id_veiculo
        description: "{{ doc('id_veiculo') }}"
        tests:
          - not_null:
              name: not_null__id_veiculo__aux_veiculo_falha_ar_condicionado
      - name: ano_fabricacao
        description: "{{ doc('ano_fabricacao') }}"
      - name: indicador_ar_condicionado
        description: "{{ doc('indicador_ar_condicionado') }}"
      - name: data_processamento_licenciamento
        description: "Data de processamento do licenciamento do veículo"
      - name: data_verificacao_regularidade
        description: "Data de verificação da regularidade do ar condicionado"
      - name: indicador_temperatura_variacao
        description: "Indicador se houve variação na temperatura transmitida pelo veículo"
      - name: indicador_temperatura_transmitida
        description: "Indicador se o veículo transmitiu dados de temperatura"
      - name: percentual_temperatura_nula_descartada
        description: "Percentual de registros de temperatura nula ou zero descartados"
      - name: percentual_temperatura_atipica_descartada
        description: "Percentual de registros de temperatura atípica descartados"
      - name: indicador_temperatura_descartada
        description: "Indicador se mais de 50% dos registros de temperatura foram descartados"
      - name: indicio_falha
        description: "Indicador de indício de falha no sistema de ar condicionado"
      - name: quantidade_dia_falha_operacional
        description: "{{ doc('quantidade_dia_falha_operacional') }}"
        tests:
          - not_null:
              name: not_null__quantidade_dia_falha_operacional__aux_veiculo_falha_ar_condicionado
      - name: datetime_ultima_atualizacao
        description: "{{ doc('datetime_ultima_atualizacao') }}"
      - name: versao
        description: "{{ doc('versao') }}"
      - name: id_execucao_dbt
        description: "{{ doc('id_execucao_dbt') }}"

# trigger coderabbit review