models:
  - name: transacao
    description: "Tabela com informações da Jaé sobre as transações realizadas no sistema de transporte municipal"
    columns:
      - name: data
        description: "{{ doc('data_transacao') }} [partição]"
        data_type: date
      - name: hora
        description: "Hora da transação"
        data_type: int64
      - name: datetime_transacao
        description: "Data e hora da transação em GMT-3"
        data_type: datetime
      - name: datetime_processamento
        description: "Data e hora de processamento da transação em GMT-3"
        data_type: datetime
      - name: datetime_captura
        description: "Timestamp de captura em GMT-3 (formato YYYY-MM-dd HH:mm:ssTZD)"
        data_type: datetime
      - name: modo
        description: "{{ doc('modo') }}"
        data_type: string
      - name: id_consorcio
        description: "{{ doc('id_consorcio') }}"
        data_type: string
      - name: consorcio
        description: "{{ doc('consorcio') }}"
        data_type: string
      - name: id_operadora
        description: "Identificador da operadora na tabela cadastro.operadoras"
        data_type: string
      - name: operadora
        description: "Nome da operadora de transporte (mascarado se for pessoa física)"
        data_type: string
      - name: id_servico_jae
        description: "Identificador da linha no banco de dados da jaé (É possível cruzar os dados com a tabela rj-smtr.cadastro.servicos usando a coluna id_servico_jae)"
        data_type: string
      - name: servico_jae
        description: "Nome curto da linha operada pelo veículo com variação de serviço (ex: 010, 011SN, ...) ou código da estação de BRT na Jaé"
        data_type: string
      - name: descricao_servico_jae
        description: "{{ doc('descricao_servico_jae') }}"
        data_type: string
      - name: sentido
        description: "{{ doc('sentido') }}"
        data_type: string
      - name: id_veiculo
        description: "{{ doc('id_veiculo') }}"
        data_type: string
      - name: id_validador
        description: "Número de série do validador"
        data_type: string
      - name: id_cliente
        description: "Identificador único do cliente [protegido]"
        policy_tags:
          - 'projects/rj-smtr/locations/us/taxonomies/6071707853840412174/policyTags/1168584191451386864'
        data_type: string
      - name: hash_cliente
        description: "Hash identificador do cliente [protegido]"
        policy_tags:
          - 'projects/rj-smtr/locations/us/taxonomies/6071707853840412174/policyTags/3266350367297582691'
        data_type: bytes
      - name: id_transacao
        description: "Identificador único da transação"
        data_type: string
      - name: tipo_transacao_jae
        description: "Tipo de transação realizada conforme o dado original da Jaé (a primeira perna de integrações são classificadas como tipo Débito e não Integração)"
        data_type: string
      - name: tipo_transacao
        description: "Tipo de transação realizada no padrão usado pela SMTR"
        data_type: string
      - name: latitude
        description: "Latitude da transação (WGS84)"
        data_type: float64
      - name: longitude
        description: "{{ doc('longitude_transacao') }}"
        data_type: float64
      - name: geo_point_transacao
        description: "Ponto geográfico do local da transação"
        data_type: geography
      - name: tile_id
        description: "Identificador do hexágono da geolocalização da transação na tabela rj-smtr.br_rj_riodejaneiro_geo.h3_res9"
      - name: stop_id
        description: "Código identificador do ponto de embarque (GTFS)"
      - name: stop_lat
        description: "Latitude do ponto de embarque (GTFS)"
      - name: stop_lon
        description: "Longitude do ponto de embarque (GTFS)"
      - name: valor_transacao
        description: "Valor debitado na transação atual (R$)"
        data_type: float64
      - name: valor_pagamento
        description: "Valor valor a ser pago pela transação (R$). Valores nulos indicam que o valor de pagamento para a transação ainda não foi calculado."
        data_type: float64
      - name: data_ordem
        description: "Data da ordem de pagamento da transação"
        data_type: date
      - name: id_ordem_pagamento_servico_operador_dia
        description: "Identificador único da tabela rj-smtr.br_rj_riodejaneiro_bilhetagem.ordem_pagamento_servico_operador_dia"
        data_type: string
      - name: id_ordem_pagamento_consorcio_operador_dia
        description: "Identificador único da tabela rj-smtr.br_rj_riodejaneiro_bilhetagem.ordem_pagamento_consorcio_operador_dia"
        data_type: string
      - name: id_ordem_pagamento_consorcio_dia
        description: "Identificador único da tabela rj-smtr.br_rj_riodejaneiro_bilhetagem.ordem_pagamento_consorcio_dia"
        data_type: string
      - name: id_ordem_pagamento
        description: "Identificador único da tabela rj-smtr.br_rj_riodejaneiro_bilhetagem.ordem_pagamento_dia"
        data_type: string
      - name: versao
        description: "{{ doc('versao') }}"
        data_type: string
      - name: id_operadora_jae
        description: Identificador único da operadora no sistema da Jaé
        data_type: string
        quote: true
      - name: hash_cartao
        description: Hash identificador do cartão [protegido]
        policy_tags:
          - 'projects/rj-smtr/locations/us/taxonomies/6071707853840412174/policyTags/1168584191451386864'
        data_type: string
        quote: true
      - name: cadastro_cliente
        description: "{{ doc('cadastro_cliente') }}"
        data_type: string
        quote: true
      - name: produto
        description: "{{ doc('produto') }}"
        data_type: string
        quote: true
      - name: produto_jae
        description: "{{ doc('produto_jae') }}"
        data_type: string
        quote: true
      - name: tipo_usuario
        description: "{{ doc('tipo_usuario') }}"
        data_type: string
        quote: true
      - name: meio_pagamento
        description: "{{ doc('meio_pagamento') }}"
        data_type: string
        quote: true
      - name: meio_pagamento_jae
        description: "{{ doc('meio_pagamento_jae') }}"
        data_type: string
        quote: true
      - name: datetime_ultima_atualizacao
        description: "{{ doc('datetime_ultima_atualizacao') }}"
        data_type: datetime
        quote: true
  - name: integracao
    description: "Tabela de integrações realizadas entre modos do sistema de transporte municipal, contendo os valores da repartição tarifária (quando houver). [Dados em fase de teste]"
    columns:
      - name: data
        description: "{{ doc('data_transacao') }} [partição]"
      - name: hora
        description: "Hora da transação"
      - name: datetime_processamento_integracao
        description: "Data e hora de processamento da integração em GMT-3"
      - name: datetime_captura
        description: "Data e hora da captura da integração em GMT-3"
      - name: datetime_transacao
        description: "Data e hora da transação em GMT-3"
      - name: intervalo_integracao
        description: "Tempo entre a perna atual da integração e a anterior em minutos"
      - name: id_integracao
        description: "Identificador único da integração"
      - name: sequencia_integracao
        description: "Sequência da transação dentro da integração"
      - name: id_integracao_sequencia
        description: "Identificador único da integração + sequência"
      - name: modo
        description: "{{ doc('modo') }}"
      - name: id_consorcio
        description: "{{ doc('id_consorcio') }}"
      - name: consorcio
        description: "{{ doc('consorcio') }}"
      - name: id_operadora
        description: "Identificador da operadora na tabela cadastro.operadoras"
      - name: operadora
        description: "{{ doc('operadora') }}"
      - name: id_servico_jae
        description: "Identificador da linha no banco de dados da jaé (É possível cruzar os dados com a tabela rj-smtr.cadastro.servicos usando a coluna id_servico_jae)"
      - name: servico_jae
        description: "Nome curto da linha operada pelo veículo com variação de serviço (ex: 010, 011SN, ...) ou código da estação de BRT na Jaé"
      - name: descricao_servico_jae
        description: "{{ doc('descricao_servico_jae') }}"
      - name: id_transacao
        description: "Identificador único da transação"
      - name: sentido
        description: "{{ doc('sentido') }}"
      - name: percentual_rateio
        description: "{{ doc('percentual_rateio') }}"
      - name: valor_rateio_compensacao
        description: "Valor a ser compensado pela ou à operadora (R$)"
      - name: valor_rateio
        description: "Valor real ganho pela operadora pela transação (R$)"
      - name: valor_transacao
        description: "Valor debitado do cartão no momento da transação (R$)"
      - name: valor_transacao_total
        description: "Valor total das transações da integração (R$)"
      - name: texto_adicional
        description: "Observação adicional"
      - name: versao
        description: "{{ doc('versao') }}"
  - name: transacao_riocard
    description: "Tabela com as transações feitas com RioCard que foram registradas pelo validador da Jaé"
    columns:
      - name: data
        description: "{{ doc('data_transacao') }} [partição]"
      - name: hora
        description: "Hora da transação"
      - name: datetime_transacao
        description: "Data e hora da transação [GMT-3]"
      - name: datetime_processamento
        description: "Data e hora de processamento da transação [GMT-3]"
      - name: datetime_captura
        description: "Timestamp de captura [GMT-3]"
      - name: modo
        description: "{{ doc('modo') }}"
      - name: id_consorcio
        description: "{{ doc('id_consorcio') }}"
      - name: consorcio
        description: "{{ doc('consorcio') }}"
      - name: id_operadora
        description: "Identificador único da operadora de transporte na tabela rj-smtr.cadastro.operadoras"
      - name: operadora
        description: "{{ doc('operadora') }}"
      - name: id_servico_jae
        description: "Identificador da linha no banco de dados da jaé (É possível cruzar os dados com a tabela rj-smtr.cadastro.servicos usando a coluna id_servico_jae)"
      - name: servico_jae
        description: "Nome curto da linha operada pelo veículo com variação de serviço (ex: 010, 011SN, ...) ou código da estação de BRT na Jaé"
      - name: descricao_servico_jae
        description: "{{ doc('descricao_servico_jae') }}"
      - name: sentido
        description: "{{ doc('sentido') }}"
      - name: id_veiculo
        description: "{{ doc('id_veiculo') }}"
      - name: id_validador
        description: "Número de série do validador"
      - name: id_transacao
        description: "Identificador único da transação"
      - name: latitude
        description: "Latitude da transação (WGS84)"
      - name: longitude
        description: "{{ doc('longitude_transacao') }}"
      - name: geo_point_transacao
        description: "Ponto geográfico do local da transação"
      - name: valor_transacao
        description: "Valor debitado na transação atual (R$)"
      - name: versao
        description: "{{ doc('versao') }}"

  - name: transacao_valor_ordem
    description: Tabela contendo o valor de cada transação em uma ordem de pagamento
    columns:
      - name: data_ordem
        description: Data da ordem de pagamento (partição)
        data_type: date
        quote: true
      - name: data_transacao
        description: "{{ doc('data_transacao') }}"
        data_type: date
        quote: true
      - name: id_transacao
        description: Identificador único da transação
        data_type: string
        quote: true
      - name: modo
        description: "{{ doc('modo') }}"
        data_type: string
        quote: true
      - name: consorcio
        description: "{{  doc('consorcio') }}"
        data_type: string
        quote: true
      - name: id_operadora
        description: Identificador da operadora na tabela cadastro.operadoras
        data_type: string
        quote: true
      - name: id_servico_jae
        description: Identificador da linha no banco de dados da jaé (É possível cruzar os dados com a tabela rj-smtr.cadastro.servicos usando a coluna id_servico_jae)
        data_type: string
        quote: true
      - name: valor_transacao_rateio
        description: Valor da transação com o rateio (se houver) (R$)
        data_type: float64
        quote: true
      - name: id_ordem_pagamento
        description: Identificador da ordem pagamento no banco de dados da Jaé
        data_type: string
        quote: true
      - name: id_ordem_pagamento_consorcio_dia
        description: Identificador único da tabela rj-smtr.br_rj_riodejaneiro_bilhetagem.ordem_pagamento_consorcio_dia
        data_type: string
        quote: true
      - name: id_ordem_pagamento_consorcio_operador_dia
        description: Identificador único da tabela rj-smtr.br_rj_riodejaneiro_bilhetagem.ordem_pagamento_consorcio_operador_dia
        data_type: string
        quote: true
      - name: versao
        description: "{{ doc('versao') }}"
        data_type: string
        quote: true
      - name: datetime_ultima_atualizacao
        description: "{{ doc('datetime_ultima_atualizacao') }}"
        data_type: datetime
        quote: true
  - name: passageiro_hora
    description: "Tabela de contagem do número de passageiros por hora."
    columns:
      - name: data
        description: "{{ doc('data_transacao') }} [partição]"
      - name: hora
        description: "Hora da transação"
      - name: modo
        description: "{{ doc('modo') }}"
      - name: consorcio
        description: "{{ doc('consorcio') }}"
      - name: id_servico_jae
        description: "Identificador da linha no banco de dados da jaé (É possível cruzar os dados com a tabela rj-smtr.cadastro.servicos usando a coluna id_servico_jae)"
      - name: servico_jae
        description: "Nome curto da linha operada pelo veículo com variação de serviço (ex: 010, 011SN, ...) ou código da estação de BRT na Jaé"
      - name: descricao_servico_jae
        description: "{{ doc('descricao_servico_jae') }}"
      - name: sentido
        description: "{{ doc('sentido') }}"
      - name: cadastro_cliente
        description: "{{ doc('cadastro_cliente') }}"
        data_type: string
        quote: true
      - name: produto
        description: "{{ doc('produto') }}"
        data_type: string
        quote: true
      - name: tipo_usuario
        description: "{{ doc('tipo_usuario') }}"
        data_type: string
        quote: true
      - name: meio_pagamento
        description: "{{ doc('meio_pagamento') }}"
        data_type: string
        quote: true
      - name: quantidade_passageiros
        description: "Quantidade de transações que aconteceram em determinada data e hora"
      - name: versao
        description: "{{ doc('versao') }}"
  - name: passageiro_tile_hora
    description: "Tabela de contagem do número de passageiros por hora dentro de um grid de geolocalização."
    columns:
      - name: data
        description: "{{ doc('data_transacao') }} [partição]"
      - name: hora
        description: "Hora da transação"
      - name: modo
        description: "Tipo de transporte (Ônibus, Van, BRT)"
      - name: consorcio
        description: "Nome do consórcio"
      - name: id_servico_jae
        description: "Identificador da linha no banco de dados da jaé (É possível cruzar os dados com a tabela rj-smtr.cadastro.servicos usando a coluna id_servico_jae)"
      - name: servico_jae
        description: "Nome curto da linha operada pelo veículo com variação de serviço (ex: 010, 011SN, ...) ou código da estação de BRT na Jaé"
      - name: descricao_servico_jae
        description: "{{ doc('descricao_servico_jae') }}"
      - name: sentido
        description: "Sentido de operação do serviço (0 = ida, 1 = volta)"
      - name: cadastro_cliente
        description: "{{ doc('cadastro_cliente') }}"
        data_type: string
        quote: true
      - name: produto
        description: "{{ doc('produto') }}"
        data_type: string
        quote: true
      - name: tipo_usuario
        description: "{{ doc('tipo_usuario') }}"
        data_type: string
        quote: true
      - name: meio_pagamento
        description: "{{ doc('meio_pagamento') }}"
        data_type: string
        quote: true
      - name: tile_id
        description: "Identificador do hexágono da geolocalização da transação na tabela rj-smtr.br_rj_riodejaneiro_geo.h3_res9"
      - name: quantidade_passageiros
        description: "Quantidade de transações que aconteceram em determinada data e hora"
      - name: versao
        description: "Código de controle de versão do dado (SHA Github)"
  - name: dicionario
    description: "Dicionário de dados"
    columns:
      - name: chave
        description: "Chave"
      - name: cobertura_temporal
        description: "{{ doc('cobertura_temporal') }}"
      - name: id_tabela
        description: "Nome da tabela"
      - name: coluna
        description: "Nome da coluna"
      - name: valor
        description: "Valor"