version: 2

models:
  - name: viagem_transacao
    description: "Tabela com quantidade de transações por viagem"
    columns:
      - name: data
        description: "{{ doc('data_viagem') }}"
      - name: id_viagem
        description: "{{ doc('id_viagem') }}"
      - name: id_veiculo
        description: "{{ doc('id_veiculo') }}"
      - name: servico
        description: "{{ doc('servico') }}"
      - name: tipo_viagem
        description: "{{ doc('tipo_viagem_status') }}"
      - name: tecnologia
        description: "{{ doc('tecnologia') }}"
      - name: distancia_planejada
        description: "{{ doc('distancia_planejada') }}"
      - name: quantidade_transacao
        description: "Quantidade de transações da Jaé registradas entre datetime_partida_bilhetagem e datetime_chegada"
      - name: quantidade_transacao_riocard
        description: "Quantidade de transações da RioCard registradas entre datetime_partida_bilhetagem e datetime_chegada"
      - name: indicador_estado_equipamento_aberto
        description: "Indicador se todos os registros de GPS foram transmitidos com o estado ABERTO entre datetime_partida e datetime_chegada"
      - name: datetime_partida_bilhetagem
        description: "Horário de início da viagem para contagem das transações, considerando uma tolerância de até 30 minutos do ínicio da viagem, limitada pelo encerramento da viagem anterior realizada pelo mesmo veículo, com adição de 1 segundo"
      - name: datetime_partida
        description: "{{ doc('datetime_partida') }}"
      - name: datetime_chegada
        description: "{{ doc('datetime_chegada') }}"
      - name: datetime_ultima_atualizacao
        description: "{{ doc('datetime_ultima_atualizacao') }}"

  - name: valor_km_tipo_viagem
    description: "Tabela de referência do valor do subsídio por tipo de viagem e tecnologia"
    tests:
      - date_overlap_tipo_viagem:
          name: date_overlap_tipo_viagem__valor_km_tipo_viagem
          where: "data_inicio between date('{date_range_start}') and date('{date_range_end}') or data_fim between date('{date_range_start}') and date('{date_range_end}')"
    columns:
      - name: status
        description: "{{ doc('tipo_viagem_status') }}"
        tests:
          - not_null:
              name: not_null__status__valor_km_tipo_viagem
              where: "data_inicio between date('{date_range_start}') and date('{date_range_end}') or data_fim between date('{date_range_start}') and date('{date_range_end}')"
      - name: tecnologia
        description: "{{ doc('tecnologia') }}"
      - name: subsidio_km
        description: "{{ doc('subsidio_km') }}"
        tests:
          - not_null:
              name: not_null__subsidio_km__valor_km_tipo_viagem
              where: "data_inicio between date('{date_range_start}') and date('{date_range_end}') or data_fim between date('{date_range_start}') and date('{date_range_end}')"
      - name: irk
        description: "{{ doc('irk') }}"
        tests:
          - not_null:
              name: not_null__irk__valor_km_tipo_viagem
              where: "data_inicio between date('{date_range_start}') and date('{date_range_end}') or data_fim between date('{date_range_start}') and date('{date_range_end}')"
      - name: data_inicio
        description: "{{ doc('data_inicio_parametros') }}"
        tests:
          - not_null:
              name: not_null__data_inicio__valor_km_tipo_viagem
              where: "data_inicio between date('{date_range_start}') and date('{date_range_end}') or data_fim between date('{date_range_start}') and date('{date_range_end}')"
      - name: data_fim
        description: "{{ doc('data_fim') }}"
      - name: indicador_penalidade_judicial
        description: "{{ doc('indicador_penalidade_judicial') }}"
      - name: legislacao
        description: "{{ doc('legislacao') }}"
  - name: percentual_operacao_faixa_horaria
    description: "Tabela com Percentual de Operação dos serviços de ônibus [SPPO] por faixa horária"
    columns:
      - name: data
        description: "{{ doc('data_gps') }}"
      - name: tipo_dia
        description: "Dia da semana considerado para o cálculo da distância planejada - categorias: Dia Útil, Sabado, Domingo"
      - name: faixa_horaria_inicio
        description: "{{ doc('faixa_horaria_inicio') }}"
      - name: faixa_horaria_fim
        description: "{{ doc('faixa_horaria_fim') }}"
      - name: consorcio
        description: "Consórcio que opera o serviço"
      - name: servico
        description: "{{ doc('servico') }}"
      - name: viagens_faixa
        description: "{{ doc('viagens_faixa') }}"
      - name: km_apurada_faixa
        description: "Distância apurada para o serviço por faixa horária (km)"
      - name: km_planejada_faixa
        description: "{{ doc('km_planejada_faixa') }}"
      - name: pof
        description: "{{ doc('pof') }}"
      - name: versao
        description: "{{ doc('versao') }}"
      - name: datetime_ultima_atualizacao
        description: "{{ doc('datetime_ultima_atualizacao') }}"
  - name: servico_contrato_abreviado
    description: "Tabela com serviços das Fases I e II, que têm prazo de contrato abreviado, conforme previsto no Anexo II do ACORDO JUDICIAL NOS AUTOS DA ACP 0045547-94.2019.8.19.0001 (FLS. 24567-24629)"
    columns:
      - name: servico
        description: "{{ doc('servico') }}"