version: 2

models:
  - name: viagem_transacao
    description: "Tabela com quantidade de transações por viagem"
    columns:
      - name: data
        description: "{{ doc('data_viagem') }} [partição]"
      - name: id_viagem
        description: "{{ doc('id_viagem') }}"
      - name: id_veiculo
        description: "{{ doc('id_veiculo') }}"
      - name: servico
        description: "{{ doc('servico') }}"
      - name: id_validador
        description: "{{ doc('id_validador') }}"
      - name: tipo_viagem
        description: "{{ doc('tipo_viagem_status') }}"
      - name: modo
        description: "{{ doc('modo') }}"
      - name: tecnologia_apurada
        description: "{{ doc('tecnologia') }}"
      - name: tecnologia_remunerada
        description: "{{ doc('tecnologia_remunerada') }}"
      - name: sentido
        description: "{{ doc('sentido') }}"
      - name: distancia_planejada
        description: "{{ doc('distancia_planejada') }}"
      - name: quantidade_transacao
        description: "Quantidade de transações da Jaé registradas entre datetime_partida_bilhetagem e datetime_chegada"
      - name: quantidade_transacao_riocard
        description: "Quantidade de transações da RioCard registradas entre datetime_partida_bilhetagem e datetime_chegada"
      - name: percentual_estado_equipamento_aberto
        description: "Percentual de registros com estado de equipamento ABERTO durante a viagem"
      - name: indicador_estado_equipamento_aberto
        description: "Indicador se todos os registros de GPS foram transmitidos com o estado ABERTO entre datetime_partida e datetime_chegada"
      - name: datetime_partida_bilhetagem
        description: "Horário de início da viagem para contagem das transações, considerando uma tolerância de até 30 minutos do ínicio da viagem, limitada pelo encerramento da viagem anterior realizada pelo mesmo veículo, com adição de 1 segundo"
      - name: datetime_partida
        description: "{{ doc('datetime_partida') }}"
      - name: datetime_chegada
        description: "{{ doc('datetime_chegada') }}"
      - name: datetime_ultima_atualizacao
        description: "{{ doc('datetime_ultima_atualizacao') }}"

  - name: valor_km_tipo_viagem
    description: "Tabela de referência do valor do subsídio por tipo de viagem e tecnologia"
    tests:
      - date_overlap_tipo_viagem:
          name: date_overlap_tipo_viagem__valor_km_tipo_viagem
          where: "data_inicio between date('{date_range_start}') and date('{date_range_end}') or data_fim between date('{date_range_start}') and date('{date_range_end}')"
    columns:
      - name: status
        description: "{{ doc('tipo_viagem_status') }}"
        tests:
          - not_null:
              name: not_null__status__valor_km_tipo_viagem
              where: "data_inicio between date('{date_range_start}') and date('{date_range_end}') or data_fim between date('{date_range_start}') and date('{date_range_end}')"
      - name: tecnologia
        description: "{{ doc('tecnologia') }}"
      - name: subsidio_km
        description: "{{ doc('subsidio_km') }}"
        tests:
          - not_null:
              name: not_null__subsidio_km__valor_km_tipo_viagem
              where: "data_inicio between date('{date_range_start}') and date('{date_range_end}') or data_fim between date('{date_range_start}') and date('{date_range_end}')"
      - name: irk
        description: "{{ doc('irk') }}"
        tests:
          - not_null:
              name: not_null__irk__valor_km_tipo_viagem
              where: "data_inicio between date('{date_range_start}') and date('{date_range_end}') or data_fim between date('{date_range_start}') and date('{date_range_end}')"
      - name: data_inicio
        description: "{{ doc('data_inicio_parametros') }}"
        tests:
          - not_null:
              name: not_null__data_inicio__valor_km_tipo_viagem
              where: "data_inicio between date('{date_range_start}') and date('{date_range_end}') or data_fim between date('{date_range_start}') and date('{date_range_end}')"
      - name: data_fim
        description: "{{ doc('data_fim') }}"
      - name: indicador_penalidade_judicial
        description: "{{ doc('indicador_penalidade_judicial') }}"
      - name: legislacao
        description: "{{ doc('legislacao') }}"
  - name: percentual_operacao_faixa_horaria
    description: "Tabela com Percentual de Operação dos serviços de ônibus [SPPO] por faixa horária"
    columns:
      - name: data
        description: "{{ doc('data_gps') }}"
      - name: tipo_dia
        description: "Dia da semana considerado para o cálculo da distância planejada - categorias: Dia Útil, Sabado, Domingo"
      - name: faixa_horaria_inicio
        description: "{{ doc('faixa_horaria_inicio') }}"
      - name: faixa_horaria_fim
        description: "{{ doc('faixa_horaria_fim') }}"
      - name: consorcio
        description: "Consórcio que opera o serviço"
      - name: servico
        description: "{{ doc('servico') }}"
      - name: viagens_faixa
        description: "{{ doc('viagens_faixa') }}"
      - name: km_apurada_faixa
        description: "Distância apurada para o serviço por faixa horária (km)"
      - name: km_planejada_faixa
        description: "{{ doc('km_planejada_faixa') }}"
      - name: pof
        description: "{{ doc('pof') }}"
      - name: versao
        description: "{{ doc('versao') }}"
      - name: datetime_ultima_atualizacao
        description: "{{ doc('datetime_ultima_atualizacao') }}"
      - name: id_execucao_dbt
        description: "{{ doc('id_execucao_dbt') }}"
      - name: sentido
        description: "{{ doc('sentido') }}"
  - name: servico_contrato_abreviado
    description: "Tabela com serviços das Fases I e II, que têm prazo de contrato abreviado, conforme previsto no Anexo II do ACORDO JUDICIAL NOS AUTOS DA ACP 0045547-94.2019.8.19.0001 (FLS. 24567-24629)"
    columns:
      - name: servico
        description: "{{ doc('servico') }}"
  - name: viagem_classificada
    description: "Tabela com classificação de viagens de ônibus [SPPO] baseado no status do veículo e autuações"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
          - data
          - id_viagem
          - id_veiculo
          name: dbt_utils.unique_combination_of_columns__viagem_classificada
          where: "data between date('{date_range_start}') and date('{date_range_end}') and data >= date('{DATA_SUBSIDIO_V15_INICIO}')"
    columns:
      - name: data
        description: "{{ doc('data_viagem') }} [partição]"
        tests:
          - not_null:
              name: not_null__data__viagem_classificada
              where: "data between date('{date_range_start}') and date('{date_range_end}') and data >= date('{DATA_SUBSIDIO_V15_INICIO}')"
      - name: id_viagem
        description: "{{ doc('id_viagem') }}"
        tests:
          - not_null:
              name: not_null__id_viagem__viagem_classificada
              where: "data between date('{date_range_start}') and date('{date_range_end}') and data >= date('{DATA_SUBSIDIO_V15_INICIO}')"
      - name: id_veiculo
        description: "{{ doc('id_veiculo') }}"
        tests:
          - not_null:
              name: not_null__id_veiculo__viagem_classificada
              where: "data between date('{date_range_start}') and date('{date_range_end}') and data >= date('{DATA_SUBSIDIO_V15_INICIO}')"
      - name: datetime_partida
        description: "{{ doc('datetime_partida') }}"
      - name: datetime_chegada
        description: "{{ doc('datetime_chegada') }}"
      - name: modo
        description: "{{ doc('modo') }}"
      - name: placa
        description: "{{ doc('placa') }}"
        tests:
          - not_null:
              name: not_null__placa__viagem_classificada
              where: "data between date('{date_range_start}') and date('{date_range_end}') and data >= date('{DATA_SUBSIDIO_V15_INICIO}') and tipo_viagem != 'Não licenciado'"
      - name: ano_fabricacao
        description: "{{ doc('ano_fabricacao') }} [chassi]"
        tests:
          - not_null:
              name: not_null__ano_fabricacao__viagem_classificada
              where: "data between date('{date_range_start}') and date('{date_range_end}') and data >= date('{DATA_SUBSIDIO_V15_INICIO}') and tipo_viagem != 'Não licenciado'"
      - name: tecnologia_apurada
        description: "{{ doc('tecnologia') }}"
        tests:
          - not_null:
              name: not_null__tecnologia_apurada__viagem_classificada
              where: "data between date('{date_range_start}') and date('{date_range_end}') and data >= date('{DATA_SUBSIDIO_V15_INICIO}') and tipo_viagem != 'Não licenciado'"
      - name: tecnologia_remunerada
        description: "{{ doc('tecnologia_remunerada') }}"
        tests:
          - not_null:
              name: not_null__tecnologia_remunerada__viagem_classificada
              where: "data between date('{date_range_start}') and date('{date_range_end}') and data >= date('{DATA_SUBSIDIO_V15_INICIO}') and tipo_viagem not in ('Não autorizado por capacidade', 'Não licenciado', 'Não vistoriado', 'Lacrado', 'Não autorizado por ausência de ar-condicionado')"
      - name: tipo_viagem
        description: "{{ doc('tipo_viagem_status') }}"
        tests:
          - not_null:
              name: not_null__tipo_viagem__viagem_classificada
              where: "data between date('{date_range_start}') and date('{date_range_end}') and data >= date('{DATA_SUBSIDIO_V15_INICIO}')"
      - name: indicadores
        description: "{{ doc('indicadores_veiculo') }}"
      - name: servico
        description: "{{ doc('servico') }}"
      - name: sentido
        description: "{{ doc('sentido') }}"
      - name: distancia_planejada
        description: "{{ doc('distancia_planejada') }}"
      - name: datetime_ultima_atualizacao
        description: "{{ doc('datetime_ultima_atualizacao') }}"
      - name: versao
        description: "{{ doc('versao') }}"
      - name: id_execucao_dbt
        description: "{{ doc('id_execucao_dbt') }}"
  - name: viagem_regularidade_temperatura
    description: "Tabela com classificação de viagens considerando regularidade da temperatura do ar condicionado"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
          - data
          - id_viagem
          - id_veiculo
          name: dbt_utils.unique_combination_of_columns__viagem_regularidade_temperatura
          where: "data between date('{date_range_start}') and date('{date_range_end}') and data >= date('{DATA_SUBSIDIO_V17_INICIO}')"
      - test_check_regularidade_temperatura:
          name: test_check_regularidade_temperatura__viagem_regularidade_temperatura
          where: "data between date('{date_range_start}') and date('{date_range_end}') and data >= date('{DATA_SUBSIDIO_V17_INICIO}')"
    columns:
      - name: data
        description: "{{ doc('data_viagem') }} [partição]"
        tests:
          - not_null:
              name: not_null__data__viagem_regularidade_temperatura
              where: "data between date('{date_range_start}') and date('{date_range_end}') and data >= date('{DATA_SUBSIDIO_V17_INICIO}')"
      - name: id_viagem
        description: "{{ doc('id_viagem') }}"
        tests:
          - not_null:
              name: not_null__id_viagem__viagem_regularidade_temperatura
              where: "data between date('{date_range_start}') and date('{date_range_end}') and data >= date('{DATA_SUBSIDIO_V17_INICIO}')"
          - dbt_utils.relationships_where:
              name: dbt_utils.relationships_where__id_viagem__viagem_regularidade_temperatura
              to: ref('viagem_classificada')
              field: id_viagem
              to_condition: "data between date('{{ var('date_range_start') }}') and date('{{ var('date_range_end') }}') and data >= date('{{ var('DATA_SUBSIDIO_V17_INICIO') }}')"
              where: "data between date('{date_range_start}') and date('{date_range_end}') and data >= date('{DATA_SUBSIDIO_V17_INICIO}')"
      - name: id_veiculo
        description: "{{ doc('id_veiculo') }}"
        tests:
          - not_null:
              name: not_null__id_veiculo__viagem_regularidade_temperatura
              where: "data between date('{date_range_start}') and date('{date_range_end}') and data >= date('{DATA_SUBSIDIO_V17_INICIO}')"
      - name: datetime_partida
        description: "{{ doc('datetime_partida') }}"
        tests:
          - not_null:
              name: not_null__datetime_partida__viagem_regularidade_temperatura
              where: "data between date('{date_range_start}') and date('{date_range_end}') and data >= date('{DATA_SUBSIDIO_V17_INICIO}')"
      - name: datetime_chegada
        description: "{{ doc('datetime_chegada') }}"
        tests:
          - not_null:
              name: not_null__datetime_chegada__viagem_regularidade_temperatura
              where: "data between date('{date_range_start}') and date('{date_range_end}') and data >= date('{DATA_SUBSIDIO_V17_INICIO}')"
      - name: modo
        description: "{{ doc('modo') }}"
      - name: ano_fabricacao
        description: "{{ doc('ano_fabricacao') }}"
        tests:
          - not_null:
              name: not_null__ano_fabricacao__viagem_regularidade_temperatura
              where: "data between date('{date_range_start}') and date('{date_range_end}') and data >= date('{DATA_SUBSIDIO_V17_INICIO}') and tipo_viagem != 'Não licenciado'"
      - name: tecnologia_apurada
        description: "{{ doc('tecnologia') }}"
        tests:
          - not_null:
              name: not_null__tecnologia_apurada__viagem_regularidade_temperatura
              where: "data between date('{date_range_start}') and date('{date_range_end}') and data >= date('{DATA_SUBSIDIO_V17_INICIO}') and tipo_viagem != 'Não licenciado'"
      - name: tecnologia_remunerada
        description: "{{ doc('tecnologia_remunerada') }}"
        tests:
          - not_null:
              name: not_null__tecnologia_remunerada__viagem_regularidade_temperatura
              where: "data between date('{date_range_start}') and date('{date_range_end}') and data >= date('{DATA_SUBSIDIO_V17_INICIO}') and tipo_viagem not in ('Não autorizado por capacidade', 'Não licenciado', 'Não vistoriado', 'Lacrado', 'Não autorizado por ausência de ar-condicionado')"
      - name: tipo_viagem
        description: "{{ doc('tipo_viagem_status') }}"
        tests:
          - not_null:
              name: not_null__tipo_viagem__viagem_regularidade_temperatura
              where: "data between date('{date_range_start}') and date('{date_range_end}') and data >= date('{DATA_SUBSIDIO_V17_INICIO}')"
      - name: indicadores
        description: "{{ doc('indicadores_viagem') }}"
        tests:
          - not_null:
              name: not_null__indicadores__viagem_regularidade_temperatura
              where: "data between date('{date_range_start}') and date('{date_range_end}') and data >= date('{DATA_SUBSIDIO_V17_INICIO}')"
      - name: servico
        description: "{{ doc('servico') }}"
        tests:
          - not_null:
              name: not_null__servico__viagem_regularidade_temperatura
              where: "data between date('{date_range_start}') and date('{date_range_end}') and data >= date('{DATA_SUBSIDIO_V17_INICIO}')"
      - name: sentido
        description: "{{ doc('sentido') }}"
        tests:
          - not_null:
              name: not_null__sentido__viagem_regularidade_temperatura
              where: "data between date('{date_range_start}') and date('{date_range_end}') and data >= date('{DATA_SUBSIDIO_V17_INICIO}')"
      - name: distancia_planejada
        description: "{{ doc('distancia_planejada') }}"
        tests:
          - not_null:
              name: not_null__distancia_planejada__viagem_regularidade_temperatura
              where: "data between date('{date_range_start}') and date('{date_range_end}') and data >= date('{DATA_SUBSIDIO_V17_INICIO}')"
      - name: datetime_ultima_atualizacao
        description: "{{ doc('datetime_ultima_atualizacao') }}"
      - name: versao
        description: "{{ doc('versao') }}"
      - name: id_execucao_dbt
        description: "{{ doc('id_execucao_dbt') }}"
