version: 2

models:
  - name: registros_status_viagem_inferida
    description: "Registros de status de GPS associados a viagens inferidas"
    columns:
      - name: data
        description: "Data da viagem [partição]"
        data_type: date
        quote: true
      - name: id_veiculo
        description: "{{ doc('id_veiculo') }}"
        data_type: string
        quote: true
      - name: id_empresa
        description: "Código identificador da empresa [extraído do id_veiculo]"
        data_type: string
        quote: true
      - name: timestamp_gps
        description: "{{ doc('timestamp_gps') }}"
        data_type: timestamp
        quote: true
      - name: timestamp_minuto_gps
        description: "Timestamp de emissão do sinal de GPS truncado em minutos"
        data_type: timestamp
        quote: true
      - name: posicao_veiculo_geo
        description: "Posição geográfica do veículo [ponto]"
        data_type: geography
        quote: true
      - name: servico_informado
        description: "Serviço informado pelo GPS"
        data_type: string
        quote: true
      - name: servico_realizado
        description: "{{ doc('servico') }}"
        data_type: string
        quote: true
      - name: shape_id
        description: "Identificador de um shape da tabela shapes do GTFS"
        data_type: string
        quote: true
      - name: sentido_shape
        description: "Sentido do shape [I - Ida, V - Volta]"
        data_type: string
        quote: true
      - name: shape_id_planejado
        description: "Identificador do shape planejado"
        data_type: string
        quote: true
      - name: trip_id
        description: "Identificador de uma viagem da tabela trips do GTFS"
        data_type: string
        quote: true
      - name: trip_id_planejado
        description: "Identificador do trip_id planejado"
        data_type: string
        quote: true
      - name: sentido
        description: "{{ doc('sentido') }}"
        data_type: string
        quote: true
      - name: start_pt
        description: "Ponto inicial do shape [geografia]"
        data_type: geography
        quote: true
      - name: end_pt
        description: "Ponto final do shape [geografia]"
        data_type: geography
        quote: true
      - name: distancia_planejada
        description: "{{ doc('distancia_planejada') }}"
        data_type: float64
        quote: true
      - name: distancia
        description: "Distância percorrida pelo veículo (m)"
        data_type: float64
        quote: true
      - name: feed_start_date
        description: "{{ doc('feed_start_date') }}"
        data_type: date
        quote: true
      - name: status_viagem
        description: "Status da posição no trajeto [start, middle, end, out]"
        data_type: string
        quote: true
      - name: indicador_intersecao_segmento
        description: "Indica se a posição intersecta com algum segmento do shape"
        data_type: boolean
        quote: true
      - name: datetime_partida
        description: "{{ doc('datetime_partida') }}"
        data_type: timestamp
        quote: true
      - name: datetime_chegada
        description: "{{ doc('datetime_chegada') }}"
        data_type: timestamp
        quote: true
      - name: distancia_inicio_fim
        description: "Distância entre o início e fim da viagem (km)"
        data_type: float64
        quote: true
      - name: id_viagem
        description: "{{ doc('id_viagem') }}"
        data_type: string
        quote: true
      - name: versao_modelo
        description: "{{ doc('versao') }}"
        data_type: string
        quote: true

  - name: viagem_inferida
    description: "Viagens inferidas a partir dos dados de GPS"
    columns:
      - name: id_viagem
        description: "{{ doc('id_viagem') }}"
        data_type: string
        quote: true
      - name: data
        description: "Data da viagem [partição]"
        data_type: date
        quote: true
      - name: id_empresa
        description: "Código identificador da empresa [extraído do id_veiculo]"
        data_type: string
        quote: true
      - name: id_veiculo
        description: "{{ doc('id_veiculo') }}"
        data_type: string
        quote: true
      - name: servico_informado
        description: "Serviço informado pelo GPS no momento da partida"
        data_type: string
        quote: true
      - name: servico_realizado
        description: "{{ doc('servico') }}"
        data_type: string
        quote: true
      - name: trip_id
        description: "Identificador de uma viagem da tabela trips do GTFS"
        data_type: string
        quote: true
      - name: shape_id
        description: "Identificador de um shape da tabela shapes do GTFS"
        data_type: string
        quote: true
      - name: sentido_shape
        description: "Sentido do shape [I - Ida, V - Volta]"
        data_type: string
        quote: true
      - name: distancia_inicio_fim
        description: "Distância entre o início e fim da viagem (km)"
        data_type: float64
        quote: true
      - name: distancia_planejada
        description: "{{ doc('distancia_planejada') }}"
        data_type: float64
        quote: true
      - name: shape_id_planejado
        description: "Identificador do shape planejado"
        data_type: string
        quote: true
      - name: trip_id_planejado
        description: "Identificador do trip_id planejado"
        data_type: string
        quote: true
      - name: sentido
        description: "{{ doc('sentido') }}"
        data_type: string
        quote: true
      - name: datetime_partida
        description: "{{ doc('datetime_partida') }}"
        data_type: timestamp
        quote: true
      - name: datetime_chegada
        description: "{{ doc('datetime_chegada') }}"
        data_type: timestamp
        quote: true
      - name: versao_modelo
        description: "{{ doc('versao') }}"
        data_type: string
        quote: true
