version: 2

models:
  - name: subsidio_faixa_servico_dia
    description: "Sumário do subsídio dos serviços de ônibus [SPPO] por dia e faixa horária"
    columns:
      - name: data
        description: "{{ doc('data_gps') }}"
      - name: tipo_dia
        description: "Dia da semana considerado para o cálculo da distância planejada - categorias: Dia Útil, Sabado, Domingo"
      - name: faixa_horaria_inicio
        description: "{{ doc('faixa_horaria_inicio') }}"
      - name: faixa_horaria_fim
        description: "{{ doc('faixa_horaria_fim') }}"
      - name: consorcio
        description: "Consórcio que opera o serviço"
      - name: servico
        description: "Serviço realizado pelo veículo"
      - name: viagens_faixa
        description: "{{ doc('viagens_faixa') }}"
      - name: km_apurada_faixa
        description: "Distância apurada para o serviço por faixa horária (km)"
      - name: km_planejada_faixa
        description: "{{ doc('km_planejada_faixa') }}"
      - name: pof
        description: "{{ doc('pof') }}"
      - name: versao
        description: "{{ doc('versao') }}"
      - name: datetime_ultima_atualizacao
        description: "{{ doc('datetime_ultima_atualizacao') }}"