version: 2

models:
  - name: pagamento_bilhetagem_jae
    description: "Tabela contendo os pagamentos realizados pela CCT aos consórcios e operadores"
    columns:
      - name: data
        description: "Data do pagamento"
      - name: datetime_pagamento
        description: "Data e hora do pagamento"
      - name: datetime_captura
        description: "Data e hora de captura [GMT-3]"
      - name: id_consorcio
        description: "Identificador do consórcio na tabela cadastro.consorcios"
      - name: id_operadora
        description: "Identificador da operadora na tabela cadastro.operadoras"
      - name: modo
        description: "Tipo de transporte (Ônibus, Van, BRT)"
      - name: favorecido
        description: "Nome do favorecido do pagamento"
      - name: data_ordem
        description: "Data da ordem de pagamento da Jaé"
      - name: id_ordem_pagamento
        description: "Identificador único da ordem de pagamento da Jaé"
      - name: valor_ordem
        description: "Valor líquido da ordem de pagamento da Jaé (R$)"
      - name: valor_pago
        description: "Valor pago (R$)"
      - name: indicador_pagamento_realizado
        description: "Indica se o pagamento foi realizado ou não"
      - name: versao
        description: "{{ doc('versao') }}"