version: 2

models:
  - name: gps_brt
    description: "Tabela com os dados tratados de registros de GPS do BRT, incluindo velocidade estimada, estado de movimento, parada em terminal ou garagem e interseção com o traçado da linha informada."
    columns:
      - name: modo
        description: "BRT – nesse arquivo só consta esse modo"
      - name: timestamp_gps
        description: "{{ doc('timestamp_gps') }}"
      - name: data
        description: "{{ doc('data_gps') }}"
      - name: hora
        description: "{{ doc('hora_gps') }}"
      - name: id_veiculo
        description: "{{ doc('id_veiculo') }}"
      - name: servico
        description: "{{ doc('servico') }}"
      - name: latitude
        description: "{{ doc('latitude_gps') }}"
      - name: longitude
        description: "{{ doc('longitude_gps') }}"
      - name: flag_em_operacao
        description: "{{ doc('flag_em_operacao') }}"
      - name: flag_em_movimento
        description: "{{ doc('flag_em_movimento') }}"
      - name: tipo_parada
        description: "{{ doc('tipo_parada') }}"
      - name: flag_linha_existe_sigmob
        description: "{{ doc('flag_linha_existe_sigmob') }}"
      - name: flag_trajeto_correto
        description: "{{ doc('flag_trajeto_correto') }}"
      - name: flag_trajeto_correto_hist
        description: "{{ doc('flag_trajeto_correto_hist') }}"
      - name: status
        description: "{{ doc('status_veiculo_gps') }}"
      - name: velocidade_instantanea
        description: "{{ doc('velocidade_instantanea') }}"
      - name: velocidade_estimada_10_min
        description: "{{ doc('velocidade_estimada_10_min') }}"
      - name: distancia
        description: "{{ doc('distancia_gps') }}"
      - name: versao
        description: "{{ doc('versao') }}"
  - name: gps_sppo
    description: "Tabela com os dados tratados de registros de GPS do SPPO, incluindo velocidade estimada, estado de movimento, parada em terminal ou garagem e interseção com o traçado da linha informada."
    tests:
      - dbt_utils.unique_combination_of_columns:
          name: unique_columns_gps_sppo
          combination_of_columns:
            - timestamp_gps
            - id_veiculo
            - servico
            - latitude
            - longitude
          config:
            where: "DATA BETWEEN DATE('{{ var('date_range_start') }}') AND DATE('{{ var('date_range_end') }}')"
    columns:
      - name: modo
        description: "SPPO – nesse arquivo só consta esse modo"
      - name: timestamp_gps
        description: "{{ doc('timestamp_gps') }}"
        tests:
          - dbt_utils.not_null_proportion:
              name: not_null_timestamp_gps
              at_least: 1
              config:
                where: DATA BETWEEN DATE("{{ var('date_range_start') }}") AND DATE("{{ var('date_range_end') }}")
      - name: data
        description: "{{ doc('data_gps') }}"
      - name: hora
        description: "{{ doc('hora_gps') }}"
      - name: id_veiculo
        description: "{{ doc('id_veiculo') }}"
        tests:
          - dbt_utils.not_null_proportion:
              name: not_null_id_veiculo
              at_least: 1
              config:
                where: DATA BETWEEN DATE("{{ var('date_range_start') }}") AND DATE("{{ var('date_range_end') }}")
      - name: servico
        description: "{{ doc('servico') }}"
        tests:
          - dbt_utils.not_null_proportion:
              name: not_null_servico
              at_least: 1
              config:
                where: DATA BETWEEN DATE("{{ var('date_range_start') }}") AND DATE("{{ var('date_range_end') }}")
      - name: latitude
        description: "{{ doc('latitude_gps') }}"
        tests:
          - dbt_utils.not_null_proportion:
              name: not_null_latitude
              at_least: 1
              config:
                where: DATA BETWEEN DATE("{{ var('date_range_start') }}") AND DATE("{{ var('date_range_end') }}")
      - name: longitude
        description: "{{ doc('longitude_gps') }}"
        tests:
          - dbt_utils.not_null_proportion:
              name: not_null_longitude
              at_least: 1
              config:
                where: DATA BETWEEN DATE("{{ var('date_range_start') }}") AND DATE("{{ var('date_range_end') }}")
      - name: flag_em_operacao
        description: "{{ doc('flag_em_operacao') }}"
      - name: flag_em_movimento
        description: "{{ doc('flag_em_movimento') }}"
      - name: tipo_parada
        description: "{{ doc('tipo_parada') }}"
      - name: flag_linha_existe_sigmob
        description: "{{ doc('flag_linha_existe_sigmob') }}"
      - name: flag_trajeto_correto
        description: "{{ doc('flag_trajeto_correto') }}"
      - name: flag_trajeto_correto_hist
        description: "{{ doc('flag_trajeto_correto_hist') }}"
      - name: status
        description: "{{ doc('status_veiculo_gps') }}"
        tests:
          - dbt_utils.not_null_proportion:
              name: not_null_status
              at_least: 1
              config:
                where: DATA BETWEEN DATE("{{ var('date_range_start') }}") AND DATE("{{ var('date_range_end') }}")
      - name: velocidade_instantanea
        description: "{{ doc('velocidade_instantanea') }}"
      - name: velocidade_estimada_10_min
        description: "{{ doc('velocidade_estimada_10_min') }}"
      - name: distancia
        description: "{{ doc('distancia_gps') }}"
      - name: versao
        description: "{{ doc('versao') }}"
  - name: gps_brt_15_minutos
    description: "Tabela com os dados tratados de registros de GPS do BRT, incluindo velocidade estimada, estado de movimento, parada em terminal ou garagem e interseção com o traçado da linha informada."
    columns:
      - name: modo
        description: "BRT – nesse arquivo só consta esse modo"
      - name: timestamp_gps
        description: "{{ doc('timestamp_gps') }}"
      - name: data
        description: "{{ doc('data_gps') }}"
      - name: hora
        description: "{{ doc('hora_gps') }}"
      - name: id_veiculo
        description: "{{ doc('id_veiculo') }}"
      - name: servico
        description: "{{ doc('servico') }}"
      - name: latitude
        description: "{{ doc('latitude_gps') }}"
      - name: longitude
        description: "{{ doc('longitude_gps') }}"
      - name: flag_em_operacao
        description: "{{ doc('flag_em_operacao') }}"
      - name: flag_em_movimento
        description: "{{ doc('flag_em_movimento') }}"
      - name: tipo_parada
        description: "{{ doc('tipo_parada') }}"
      - name: flag_linha_existe_sigmob
        description: "{{ doc('flag_linha_existe_sigmob') }}"
      - name: flag_trajeto_correto
        description: "{{ doc('flag_trajeto_correto') }}"
      - name: flag_trajeto_correto_hist
        description: "{{ doc('flag_trajeto_correto_hist') }}"
      - name: status
        description: "{{ doc('status_veiculo_gps') }}"
      - name: velocidade_instantanea
        description: "{{ doc('velocidade_instantanea') }}"
      - name: velocidade_estimada_10_min
        description: "{{ doc('velocidade_estimada_10_min') }}"
      - name: distancia
        description: "{{ doc('distancia_gps') }}"
      - name: versao
        description: "{{ doc('versao') }}"
  - name: gps_sppo_15_minutos
    description: "Tabela com os dados tratados de registros de GPS do SPPO da última hora e 15 minutos, incluindo velocidade estimada, estado de movimento, parada em terminal ou garagem e interseção com o traçado da linha informada."
    columns:
      - name: modo
        description: "SPPO – nesse arquivo só consta esse modo"
      - name: timestamp_gps
        description: "{{ doc('timestamp_gps') }}"
      - name: data
        description: "{{ doc('data_gps') }}"
      - name: hora
        description: "{{ doc('hora_gps') }}"
      - name: id_veiculo
        description: "{{ doc('id_veiculo') }}"
      - name: servico
        description: "{{ doc('servico') }}"
      - name: latitude
        description: "{{ doc('latitude_gps') }}"
      - name: longitude
        description: "{{ doc('longitude_gps') }}"
      - name: flag_em_operacao
        description: "{{ doc('flag_em_operacao') }}"
      - name: flag_em_movimento
        description: "{{ doc('flag_em_movimento') }}"
      - name: tipo_parada
        description: "{{ doc('tipo_parada') }}"
      - name: flag_linha_existe_sigmob
        description: "{{ doc('flag_linha_existe_sigmob') }}"
      - name: flag_trajeto_correto
        description: "{{ doc('flag_trajeto_correto') }}"
      - name: flag_trajeto_correto_hist
        description: "{{ doc('flag_trajeto_correto_hist') }}"
      - name: status
        description: "{{ doc('status_veiculo_gps') }}"
      - name: velocidade_instantanea
        description: "{{ doc('velocidade_instantanea') }}"
      - name: velocidade_estimada_10_min
        description: "{{ doc('velocidade_estimada_10_min') }}"
      - name: distancia
        description: "{{ doc('distancia_gps') }}"
      - name: versao
        description: "{{ doc('versao') }}"
