version: 2

models:
  - name: transacao_cct
    description: "Transações para apuração do CCT."
    columns:
      - name: id_transacao
        description: "{{ doc('id_transacao') }}"
      - name: data
        description: "{{ doc('data') }}"
      - name: datetime_transacao
        description: "{{ doc('datetime_transacao') }}"
      - name: consorcio
        description: "{{ doc('consorcio') }}"
      - name: valor_pagamento
        description: "Valor do pagamento da transação."
      - name: id_ordem_pagamento
        description: "Identificador da ordem de pagamento."
      - name: id_ordem_pagamento_consorcio_operador_dia
        description: "Identificador único da ordem de pagamento por consorcio, operador e dia."
      - name: datetime_ultima_atualizacao
        description: "{{ doc('datetime_ultima_atualizacao') }}"
