version: 2

models:
  - name: viagem_informada
    description: "Detalhes das viagens informadas pelas operadoras de ônibus"
    columns:
      - name: data
        description: "{{ doc('data_viagem') }} [partição]"
      - name: datetime_partida
        description: "Data e hora da partida da viagem [GMT-3]"
      - name: datetime_chegada
        description: "Data e hora da chegada da viagem [GMT-3]"
      - name: datetime_processamento
        description: "Data e hora do processamento da viagem [GMT-3]"
      - name: datetime_captura
        description: "Data e hora da captura da integração [GMT-3]"
      - name: id_veiculo
        description: "{{ doc('id_veiculo') }}"
      - name: trip_id
        description: "Identificador de uma viagem da tabela trips do GTFS"
      - name: route_id
        description: "Identificador de uma rota da tabela routes do GTFS"
      - name: shape_id
        description: "{{ doc('shape_id') }}"
      - name: servico
        description: "{{ doc('servico_variacao') }}"
      - name: sentido
        description: "Ida ou Volta"
      - name: id_viagem
        description: "{{ doc('id_viagem') }}"
      - name: versao
        description: "{{ doc('versao') }}"
      - name: datetime_ultima_atualizacao
        description: "{{ doc('datetime_ultima_atualizacao') }}"